### PR TITLE
Fix race conditions in tests

### PR DESCRIPTION
**Pull request by tgoyne**
Consistently use dispatch_sync(queue, ^{}); to wait for a previously async thing on the queue as the other approaches used didn't guarantee that the block would be released before the test ended, resulting in RLMRealm instances sometimes being deallocated on the wrong thread and throwing an exception.

Might be why tests are sometimes breaking on master.

@alazier

### CODE REVIEW

**Comment by alazier** [comment]
:+1:

**Comment by alazier** [comment]
Lets hope this actually fixes the ci issues. Think it has a good chance.

**Comment by segiddins** [comment]
According to the docs on `dispatch_group_async`, `This function performs a Block_copy and Block_release on behalf of the caller.`.

**Comment by alazier** [comment]
I think the `dispatch_group_async` was fine, but isn't needed for only one async method since we do a `dispatch_sync` at the end.

**Comment by tgoyne** [comment]
The dispatch_group_async was the only one I actually saw problems from. I'm not entire sure how, but the deallocation of the group (which happened on one of the libdispatch control queues) was leading to an RLMRealm being deallocated on that thread.

**Pull request merged**
