### PR TITLE
[RLMRealm] Throw a helpful exception when attempting to use encryptio…

### PR DESCRIPTION
**Pull request by segiddins**
…n on watchOS

\c @jpsim

### CODE REVIEW

**Comment by jpsim** [comment]
Debugger and watchOS checks should go in `validatedKey` IMO.

**Comment by segiddins** [comment]
@jpsim done

**Comment by jpsim** [comment]
iOS Swift encryption test is failing.

**Comment by jpsim** [comment]
CI failure is unrelated (hanging compilation in iOS Swift 1.2 release, which passes locally). Merging.

**Pull request merged**
