### PR TITLE
[Examples] moved installation examples into this repo

### PR DESCRIPTION
**Pull request by jpsim**
From our conversation this morning during the cocoa meeting. /cc @segiddins 

Only the first of several steps defined here: https://github.com/realm/realm-cocoa-private/issues/73

### CODE REVIEW

**Comment by segiddins** [comment]
Can we add a `build.sh` command to run the installation examples?

**Comment by segiddins** [comment]
> update "package-examples" in build.sh to remove examples/installation

**Comment by jpsim** [comment]
> Can we add a `build.sh` command to run the installation examples?

I don't think that's necessary... in any case, I've updated `build.sh`'s "package-examples" job to ignore `examples/installation`

**Comment by jpsim** [comment]
@segiddins could you review this again please?

**Comment by segiddins** [comment]
:+1:

**Pull request merged**
