### PR TITLE
[ObjectSchemaInitialization] Allow declaring swift list properties as…

### LINKED ISSUE #1844: Using duplicate property definitions in models should throw a more descriptive exception message
I can't instantiate Realm at all, I just get this assertion:

let r = Realm() // It fails already here!

Assertion failed: (props.count == [NSSet setWithArray:[props valueForKey:@"name"]].count), function +[RLMObjectSchema schemaForObjectClass:], file /Users/realmpro/workspace/Package iOS Swift/tightdb_objc/Realm/RLMObjectSchema.mm, line 102.

### PR DESCRIPTION
**Pull request by segiddins**
… dynamic var

Closes #1844.

\c @tgoyne

### CODE REVIEW

**Comment by tgoyne** [comment]
:+1:

**Comment by jpsim** [comment]
This should really have a changelog entry and the docs/examples/samples should be updated to reflect this.

Even though the old dynamic-less approach still works, we should be nudging users towards the unified dynamic approach to keep things A) easy to understand and B) easier for us to deprecate the old dynamic-less approach.

**Comment by segiddins** [comment]
I'm not really comfortable with saying this is 100% supported, as the Xcode/Swift release notes never said it officially should work.

**Comment by jpsim** [comment]
I've posted on the Apple developer forums to evaluate whether or not this is expected behavior: https://devforums.apple.com/thread/270405

**Comment by tgoyne** [comment]
I'd somewhat prefer to wait to actively tell people to use `dynamic` until we're sure that we can switch to the less hacky dynamic-required approach.

**Comment by jpsim** [comment]
Ok, let's wait before recommending a switch.

**Comment by jpsim** [comment]
:+1:

**Pull request merged**
