### PR TITLE
Update to core 0.100.4

### LINKED ISSUE #3540: Realm 0.101: fails querying objects from read-only db in background threads
I ran into this pretty severe issue which appeared in Realm 0.101 (or maybe 0.100, didn't test with previous version): using a database in read-only mode only yields query results from the main thread. Querying the database from a background threads yields empty results sets.

## Expected Results

In Realm version prior to 0.100 this used to work just fine (I have a read-only DB in the application with static contents, alongside a read-write DB with dynamic contents).

## Actual Results

With Realm 0.101, querying the read-only DB in a background thread returns empty result sets

## Steps to Reproduce

Attached is a sample project that demonstrates the issue. It creates a simple DB, then closes it, then opens it read-only from two different queues (main and background) and only the main queue read returns query results for the objects written to the database.

With attached project:
```shell
$ pod install
$ open RealmStaticDBCrash.xcworkspace
```

Then build & run for simulator (iPhone 6S Plus, iOS 9.3). Test results are displayed in Xcode console.

## Code Sample

See attached project.
[RealmStaticDBCrash.zip](https://github.com/realm/realm-cocoa/files/255518/RealmStaticDBCrash.zip)

## Version of Realm and Tooling

Realm version: 0.101.0

Xcode version: 7.3.1 OS X 10.11.4

iOS/OSX version: iOS simulator 9.3

Dependency manager + version: CocoaPods 0.39.0

### LINKED ISSUE #3547: Queries involving multiple levels of inverse relationships hit assertion failure in core
A user provided the following test case via email that reproducibly asserts:
```swift
class A: Object {
   dynamic var id = 0
    dynamic var name = ""
    let list = List<B>()
}

class B: Object {
    dynamic var name = ""
    let list = List<C>()
    let source = LinkingObjects(fromType: A.self, property: "list")
}

class C: Object {
    dynamic var name = ""
    let source = LinkingObjects(fromType: B.self, property: "list")
}

let realm = try! Realm()
return realm.objects(C).filter("ANY source.source.id == 1")
```

### PR DESCRIPTION
**Pull request by tgoyne**
Fixes #3540. Fixes #3547.

### CODE REVIEW

**Comment by tgoyne** [comment]
CI failures are unrelated to the changes in this branch, and I'm poking at them in https://github.com/realm/realm-cocoa/pull/3578.

**Comment by tgoyne** [comment]
@bdash @jpsim

**Comment by bdash** [comment]
Thanks for taking care of writing the test cases for the query fix.

👍

**Comment by jpsim** [comment]
👍

**Pull request merged**
