### PR TITLE
Work around Xcode 7.2.1 failing to run tests in the iOS simulator for unknown reasons

### PR DESCRIPTION
**Pull request by bdash**
Resetting the simulator between the two xcodebuild invocations in the workaround for <rdar://problem/23055637> works around the new issue.

### CODE REVIEW

**Comment by bdash** [comment]
It looks like this somehow causes problems for the tvOS build on Travis. After running reset-simulators.sh it can no longer find the tvOS simulator. Huh. Jenkins looks fine. Perhaps this is due to which Xcode version is the default in the different environments?

**Comment by bdash** [comment]
I've not been able to reproduce the Travis tvOS issue locally :disappointed:

**Comment by bdash** [comment]
Ok, so what appears to be happening is that reset-simulators.sh thinks that the tvOS 9.1 simulator is a duplicate of the tvOS 9.0 simulator, and so it deletes it. reset-simulators.sh needs to be smarter about this.

**Comment by bdash** [comment]
This is ready for review now!

/cc @jpsim @tgoyne

**Comment by tgoyne** [comment]
:+1:

**Comment by jpsim** [comment]
:+1: :100:

**Pull request merged**
