### PR TITLE
fix bash scoping issue

### PR DESCRIPTION
**Pull request by larkost**

### CODE REVIEW

**Comment by austinzheng** [comment]
The object server test failure is an example of https://github.com/realm/ci/issues/145 and unrelated to this commit.

**Comment by larkost** [comment]
@austinzheng I am not sure what you are trying to say, but this one is straightforward. What is described in realm/ci#145 is not similar to this problem, or related to this fix.

**Comment by austinzheng** [comment]
Right, I am saying you can ignore the object server failure because it's unrelated to the fix you're making here.

**Comment by larkost** [comment]
Neither of these failures is related, so we are good here.

**Pull request merged**
