### PR TITLE
Fix for invalid property comparison and reuse during column reorder and migrations

### PR DESCRIPTION
**Pull request by alazier**
Still needs more testing.

@tgoyne

### CODE REVIEW

**Comment by tgoyne** [comment]
Can the copy for the accessor cache also be a shallow copy? It seems like it should be able to.

**Comment by tgoyne** [comment]
Added some tests which fail on master that this fixes.

**Comment by alazier** [comment]
@tgoyne  The accessor cache schema can be used directly and not mutated.

In general this set of optimizations worries me. They seem to easily risk unintended consequences with future changes. How large is the gain exactly? If schema copying is really a huge deal we can probably remove some of the copies done in RLMCreateTables as well.

**Comment by tgoyne** [comment]
The copy for the accessor class is probably totally irrelevant performance-wise. I was mostly just wondering if I was missing something that made it necessary.

**Comment by alazier** [comment]
I was talking about this set of optimizations, on the accessor on in particular.

I made the change to use the accessor schema directly. Since it is't mutated this should be fine. Also remove the copy from in RLMCreateTables as well. This speed up the testRealmCreation test by 5-10% on the mac - not sure what it will do on the phone.

I'm pretty sure this is safe - ie we make a deep copy if anyone ever needs to mutate properties, and shallow copy for separate table caches, but please review carefully.

**Comment by tgoyne** [comment]
:+1:

**Pull request merged**
