### PR TITLE
Test v0.96.3

### PR DESCRIPTION
**Pull request by tgoyne**

### CODE REVIEW

**Comment by jpsim** [comment]
One problem is that this doesn't include #2817 and CI machines no longer have appledoc installed. We can either c-p #2817 or install appledoc on the CI workers.

**Comment by jpsim** [comment]
Any particular reason not to add #2759, #2822, #2811, #2870, #2796 & #2828? Those aren't breaking changes.

**Comment by tgoyne** [comment]
Those all look fine. I didn't include them because they're all missing changelog entries.

**Comment by jpsim** [comment]
0.96.3 is out!

**Pull request closed without merging**
