### PR TITLE
Delete realm rather than run migration if deleteRealmIfMigrationNeeded is set

### LINKED ISSUE #3583: Make deleteRealmIfMigrationNeeded delete the file regardless of schema version changes
It might not be obvious that even if `deleteRealmIfMigrationNeeded` is set to true, migrations are still executed if a higher schema version is specified. We should point out in the API docs, that the Realm file is just deleted if there are outstanding migrations beyond those which are specified with the configuration.

/c @kishikawakatsumi @icanzilb

### PR DESCRIPTION
**Pull request by jpsim**
Closes #3583 /cc @kishikawakatsumi @tgoyne @bdash

### CODE REVIEW

**Comment by kishikawakatsumi** [comment]
Implementation is 👍 

For tests, I worried about testing only one code path that custom schema was set. It would be nice if there is a test for another code path not to set custom schema. @jpsim

**Comment by mrackwitz** [comment]
Any objections on documenting that even more in detail?

>Recreate the Realm file with the current schema if a migration would be required. This is the case, when the stored schema differs from the provided schema or the stored schema version differs from the version on this configuration. This prevents that schema migration take place.
>Note: This doesn't disable file format migrations.

**Comment by jpsim** [comment]
> For tests, I worried about testing only one code path that custom schema was set

Since we have other tests that cover custom vs shared schema code paths, it's unnecessary to duplicate here IMO.

**Comment by jpsim** [comment]
Thanks for the suggestions to improve documentation @mrackwitz, I've made some modifications.

**Comment by tgoyne** [comment]
👍 

Swiftlint is complaining about trailing whitespace.

**Pull request merged**
