### PR TITLE
Fix dispatch SyncUser.logIn completion callback to the main thread

### PR DESCRIPTION
**Pull request by stel**
Initially this issue was addressed in https://github.com/realm/realm-cocoa-private/issues/186, so I've added a test to handle this in the future.

/cc @austinzheng, @jpsim

### CODE REVIEW

**Comment by jpsim** [comment]
We discussed this IRL, but will share my thinking here again.

There's overhead to dispatching to a different queue. With this change, that overhead is applied to all our users, regardless of whether or not they need to process the results of the callback on the main queue or a background queue.

By not making any assumptions regarding what queue our users want to handle the results, we can avoid that overhead, and finally, there's very little boilerplate to dispatching to the main queue with GCD: `DispatchQueue.main.async { ... }`.

---

What _could_ be done, however, is providing an optional default argument of `callbackQueue: DispatchQueue? = .main`, since the vast majority of users will want to handle the callback on the main queue, but this still leaves the flexibility for users wanting to avoid that overhead to pass in `callbackQueue: nil`.

**Comment by austinzheng** [comment]
I'm in favor of the optional argument with default of `.main` approach. Would solve the most common case transparently, and allow flexibility for testing (where we can't dispatch to the main queue with the way our Cocoa ROS tests are currently structured) or custom behavior.

**Comment by stel** [comment]
Didn't notice https://github.com/realm/realm-cocoa/issues/4338, looks like the best place to track this.

**Comment by jpsim** [comment]
@stel please delete this branch if you're done with it.

**Pull request closed without merging**
