### PR TITLE
fix Carthage by making a Realm.xcworkspace

### LINKED ISSUE #4042: Building Realm from source with Carthage builds PlaygroundFrameworkWrapper
```
$ cat Cartfile
github "realm/realm-cocoa" "master"
$ xcode-select -p
/Applications/Xcode-7.3.1.app/Contents/Developer
$ carthage version
0.17.2
$ carthage bootstrap --platform ios --no-use-binaries
*** No Cartfile.resolved found, updating dependencies
*** Fetching realm-cocoa
*** Checking out realm-cocoa at "3f0c6f8d3a6537b359afb58e02cde108ccaa499d"
*** xcodebuild output can be found in /var/folders/np/5y4sgt8x3r13sk7x0n31z_3m0000gn/T/carthage-xcodebuild.R0DNGa.log
*** Building scheme "RealmSwift" in RealmExamples.xcworkspace
*** Building scheme "Realm" in RealmExamples.xcworkspace
*** Building scheme "PlaygroundFrameworkWrapper" in RealmExamples.xcworkspace
```

### PR DESCRIPTION
**Pull request by jpsim**
Fixes #4042. /cc @bdash 

I'm hoping to fix Carthage's logic to resolve which Xcode workspace/project to use to prefer root-level things over workspaces.

### CODE REVIEW

**Comment by bdash** [comment]
Were you able to test if putting the workspace in a `.carthage` directory works? It'd be nice to hide the workspace since it's otherwise unnecessary (and will interfere with my ability to tab complete the Xcode project path from the Terminal 😢).

**Comment by jpsim** [comment]
> Were you able to test if putting the workspace in a `.carthage` directory works?

Yes I tested it, no it didn't work 😞. I guess Carthage doesn't look in hidden directories. Putting it in `Carthage/` would work though.

**Comment by plasmLC** [comment]
@jpsim, this fix doesn't work... I've cleaned carthage cache and tried to build this branch:

> *** Building scheme "Realm" in Realm.xcworkspace
*** Building scheme "RealmSwift" in Realm.xcworkspace
*** Building scheme "PlaygroundFrameworkWrapper" in RealmExamples.xcworkspace
** CLEAN FAILED **
> 
> 
The following build commands failed:
       	Check dependencies
(1 failure)
** BUILD FAILED **
> 
> 
The following build commands failed:
       	Check dependencies
(1 failure)
warning: no umbrella header found for target 'PlaygroundFrameworkWrapper', module map will not be generated
warning: no umbrella header found for target 'PlaygroundFrameworkWrapper', module map will not be generated
A shell task (/usr/bin/xcrun xcodebuild -workspace /.../Carthage/Checkouts/realm-cocoa/examples/ios/swift-2.2/RealmExamples.xcworkspace -scheme PlaygroundFrameworkWrapper -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **
> 
> 
The following build commands failed:
       	Check dependencies
(1 failure)
** BUILD FAILED **
> 
> 
> 
The following build commands failed:
       	Check dependencies
(1 failure)

New .xcworkspace is recognised successfully but `RealmExamples.xcworkspace` is recognised too since it contains shared frameworks scheme, I suppose.

I really need this stuff cause I'm using Xcode 8, so complied binaries are not compatible for me.

**Comment by simonrice** [comment]
@jpsim I've been getting difference errors with Xcode 8 GM - I think these errors are relating from changes between Beta 6 & GM that need to be applied:

```
*** Building scheme "RealmSwift" in Realm.xcworkspace
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
/withheld/Carthage/Checkouts/realm-cocoa/RealmSwift/Realm.swift:633:39: error: @escaping may only be applied to parameters of function type
/withheld/Carthage/Checkouts/realm-cocoa/RealmSwift/Migration.swift:112:13: error: closure use of non-escaping parameter 'block' may allow it to escape
/withheld/Carthage/Checkouts/realm-cocoa/RealmSwift/Migration.swift:196:9: error: closure use of non-escaping parameter 'migrationBlock' may allow it to escape
/withheld/Carthage/Checkouts/realm-cocoa/RealmSwift/Realm.swift:482:17: error: closure use of non-escaping parameter 'block' may allow it to escape
A shell task (/usr/bin/xcrun xcodebuild -workspace /withheld/Carthage/Checkouts/realm-cocoa/Realm.xcworkspace -scheme RealmSwift -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

**Comment by kevinmlong** [comment]
So what the solution here for folks in the interim until an official Swift 3 compatible release is made?

**Comment by jpsim** [comment]
Hmm, I see Carthage still picks up other workspaces... That's unfortunate. Looking into a different fix now.

**Comment by kevinmlong** [comment]
Thanks @jpsim!

**Comment by jpsim** [comment]
@kevinmlong this branch should work now.

**Comment by jpsim** [comment]
@bdash unsharing the PlaygroundFrameworkWrapper scheme is the best solution I found. Care to review again?

**Comment by bdash** [comment]
👍

**Comment by kevinmlong** [comment]
That seemed to work! Thanks!  👍

**Comment by kevinmlong** [comment]
Thanks again @jpsim - what's the likelihood a Swift 3 release will be provided soon?

**Comment by jpsim** [comment]
We're making an official release later this week with a finalized Swift 3 APIs and binaries built with Xcode 8 GM (or final, if it's available). We announced this last week on Twitter: https://twitter.com/realm/status/773665653580496896 and https://twitter.com/realm/status/773665903946952704

**Comment by kevinmlong** [comment]
Thanks @jpsim for the links above!

**Pull request merged**
