### PR TITLE
[WIP] Consolidate to a single Xcode project

### PR DESCRIPTION
**Pull request by segiddins**
Successor to https://github.com/realm/realm-cocoa/pull/2323.
~~Blocked by https://github.com/Carthage/Carthage/pull/622.~~

### CODE REVIEW

**Comment by segiddins** [comment]
I'd love to get some eyes on this, so we can merge it if it passes, @bdash @tgoyne.

**Comment by tgoyne** [comment]
Running tests on device from Xcode doesn't work.

**Comment by bdash** [comment]
As we talked about on Slack, it looks like d178c85 will prevent the tests from running on devices from within Xcode. It also contains changes to make TestHost build on OS X despite never doing so.

**Comment by bdash** [comment]
The Realm.framework target in the Xcode project appears to contain some configuration settings that are redundant given those in Realm.xcconfig, and some others that could be moved to the .xcconfig.

**Comment by segiddins** [comment]
Closing because, sadly, I can't make this work with either iOS 7 or the device tests.

**Pull request closed without merging**
