### PR TITLE
Merge master to master-3.0

### PR DESCRIPTION
**Pull request by bdash**
This PR is primarily for CI to chew on.

There were a few conflicts in the merge that it might be worth looking over. You can see how I resolved them in this three-way diff below:
```diff3
commit ce2dfa345b44594854d60141744e9888421b658f
Merge: 6e18d043b 76f0f67e5
Author: Mark Rowe <mar@realm.io>
Date:   Fri Sep 15 12:06:52 2017 -0700

    Merge remote-tracking branch 'origin/master' into master-3.0

diff --cc CHANGELOG.md
index bc9f6b708,635bc66b3..d2160276c
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@@ -1,196 -1,16 +1,209 @@@
 +x.x.x Release notes (yyyy-MM-dd)
 +=============================================================
 +
 +### Breaking Changes
 +
 +* Rename `List.remove(objectAtIndex:)` to `List.remove(at:)` to match the name
 +  used by 'RangeReplaceableCollection'.
 +* Rename `List.swap()` to `List.swapAt()` to match the name used by 'Array'.
 +* Loosen `RLMArray` and `RLMResults`'s generic constraint from `RLMObject` to
 +  `NSObject`. This may result in having to add some casts to disambiguate
 +  types.
 +* Remove `RLMPropertyTypeArray` in favor of a separate bool `array` property on
 +  `RLMProperty`/`Property`.
 +* Remove `RLMSyncPermissionResults`. `RLMSyncPermission`s are now vended out
 +  using a `RLMResults`. This results collection supports all normal collection
 +  operations except for setting values using KVO (since `RLMSyncPermission`s are
 +  immutable) and the property aggregation operations.
 +* `RealmCollection`'s associated type `Element` has been renamed `ElementType`.
 +* Realm Swift collection types (`List`, `Results`, `AnyRealmCollection`, and
 +  `LinkingObjects` have had their generic type parameter changed from `T` to
 +  `Element`).
 +* `RealmOptional`'s generic type parameter has been changed from `T` to `Value`.
 +
 +### Enhancements
 +
 +* None.
 +
 +### Bugfixes
 +
 +* Realm Swift APIs that filter or look up the index of an object based on a
 +  format string now properly handle optional arguments in their variadic argument
 +  list.
 +
 +3.0.0-beta.3 Release notes (2017-08-23)
 +=============================================================
 +
 +### Breaking Changes
 +
 +* iOS 7 is no longer supported.
 +* Computed properties on Realm object types are detected and no
 +  longer added to the automatically generated schema.
 +* `-[RLMRealm addOrUpdateObjectsInArray:]` has been renamed to
 +  `-[RLMRealm addOrUpdateObjects:]` for consistency with similar methods
 +  that add or delete objects.
 +* `-[RLMRealm addOrUpdateObjects:]` and `-[RLMRealm deleteObjects:]` now
 +  require their argument to conform to `NSFastEnumeration`, to match similar
 +  APIs that also take collections.
 +* Remove deprecated `{RLM}SyncPermission` and `{RLM}SyncPermissionChange`
 +  classes.
 +* `{RLM}SyncPermissionValue` has been renamed to just `{RLM}SyncPermission`.
 +  Its `userId` property has been renamed `identity`, and its
 +  `-initWithRealmPath:userID:accessLevel:` initializer has been renamed
 +  `-initWithRealmPath:identity:accessLevel:`.
 +* Remove deprecated `-[RLMSyncUser permissionRealmWithError:]` and
 +  `SyncUser.permissionRealm()` APIs. Use the new permissions system.
 +* Remove deprecated error `RLMSyncErrorBadResponse`. Use
 +  `RLMSyncAuthErrorBadResponse` instead.
 +* The way interactive sync errors (client reset and permission denied)
 +  are delivered to the user has been changed. Instead of a block which can
 +  be invoked to immediately delete the offending Realm file, an opaque
 +  token object of type `RLMSyncErrorActionToken` will be returned in the
 +  error object's `userInfo` dictionary. This error object can be passed
 +  into the new `+[RLMSyncSession immediatelyHandleError:]` API to delete
 +  the files.
 +* Remove `-[NSError rlmSync_clientResetBlock]` and
 +  `-[NSError rlmSync_deleteRealmBlock]` APIs.
 +* The return types of the `SyncError.clientResetInfo()` and
 +  `SyncError.deleteRealmUserInfo()` APIs have been changed. They now return
 +  `RLMSyncErrorActionToken`s or `SyncError.ActionToken`s instead of closures.
 +* The (erroneously added) instance property `Object.className` has been
 +  removed.
 +* The class methods `Object.className()`, `Object.objectUtilClass()`, and
 +  the property `Object.isInvalidated` can no longer be overriden.
 +* The callback which runs when a sync user login succeeds or fails
 +  now runs on the main queue by default, or can be explicitly specified
 +  by a new `callbackQueue` parameter on the `{RLM}SyncUser.logIn(...)` API.
 +* Rename `{RLM}NotificationToken.stop()` to `invalidate()` and
 +  `{RealmCollection,SyncPermissionResults}.addNotificationBlock(_:)` to
 +  `observe(_:)` to mirror Foundation's new KVO APIs.
 +* The `RLMSyncProgress` enum has been renamed `RLMSyncProgressMode`.
 +* Remove deprecated `{RLM}SyncManager.disableSSLValidation` property. Disable
 +  SSL validation on a per-Realm basis by setting the `enableSSLValidation`
 +  property on `{RLM}SyncConfiguration` instead.
 +* Fix empty strings, binary data, and null on the right side of `BEGINSWITH`,
 +  `ENDSWITH` and `CONTAINS` operators in predicates to match Foundation's
 +  semantics of never matching any strings or data.
 +* Swift `Object` comparison and hashing behavior now works the same way as
 +  that of `RLMObject` (objects are now only considered equatable if their
 +  model class defines a primary key).
 +* Fix the way the hash property works on `Object` when the object model has
 +  no primary key.
 +* Fix an issue where if a Swift model class defined non-generic managed
 +  properties after generic Realm properties (like `List<T>`), the schema
 +  would be constructed incorrectly. Fixes an issue where creating such
 +  models from an array could fail.
 +
 +### Enhancements
 +
 +* Add Swift `Object.isSameObject(as:_)` API to perform the same function as
 +  the existing Objective-C API `-[RLMObject isEqualToObject:]`.
 +* Expose additional authentication-related errors that might be reported by
 +  a Realm Object Server.
 +* An error handler can now be registered on `{RLM}SyncUser`s in order to
 +  report authentication-related errors that affect the user.
 +
 +### Bugfixes
 +
 +* Sync users are now automatically logged out upon receiving certain types
 +  of errors that indicate they are no longer logged into the server. For
 +  example, users who are authenticated using third-party credentials will find
 +  themselves logged out of the Realm Object Server if the third-party identity
 +  service indicates that their credential is no longer valid.
 +* Address high CPU usage and hangs in certain cases when processing collection
 +  notifications in highly-connected object graphs.
 +
 +3.0.0-beta.2 Release notes (2017-07-26)
 +=============================================================
 +
 +### Breaking Changes
 +
 +* Remove the following deprecated Objective-C APIs:
 +  `-[RLMArray sortedResultsUsingProperty:ascending:]`,
 +  `-[RLMCollection sortedResultsUsingProperty:ascending:]`,
 +  `-[RLMResults sortedResultsUsingProperty:ascending:]`,
 +  `+[RLMSortDescriptor sortDescriptorWithProperty:ascending:]`,
 +  `RLMSortDescriptor.property`.
 +  These APIs have been superseded by equivalent APIs that take
 +  or return key paths instead of property names.
 +* Remove the following deprecated Objective-C API:
 +  `+[RLMRealm migrateRealm:configuration:]`.
 +  Please use `+[RLMRealm performMigrationForConfiguration:error:]` instead.
 +* Remove the following deprecated Swift APIs:
 +  `AnyRealmCollection.sorted(byProperty:, ascending:)`,
 +  `LinkingObjects.sorted(byProperty:, ascending:)`,
 +  `List.sorted(byProperty:, ascending:)`,
 +  `Results.sorted(byProperty:, ascending:)`,
 +  `SortDescriptor.init(property:, ascending:)`,
 +  `SortDescriptor.property`.
 +  These APIs have been superseded by equivalent APIs that take
 +  or return key paths instead of property names.
 +* The Objective-C and Swift `create(_:, value: update:)` APIs now
 +  correctly nil out nullable properties when updating an existing
 +  object when the `value` argument specifies nil or `NSNull` for
 +  the property value.
 +
 +### Enhancements
 +
 +* It is now possible to create and log in multiple Realm Object Server users
 +  with the same identity if they originate from different servers. Note that
 +  if the URLs are different aliases for the same authentication server each
 +  user will still be treated as separate (e.g. they will have their own copy
 +  of each synchronized Realm opened using them). It is highly encouraged that
 +  users defined using the access token credential type be logged in with an
 +  authentication server URL specified; this parameter will become mandatory
 +  in a future version of the SDK.
 +* Add `-[RLMSyncUser retrieveInfoForUser:identityProvider:completion:]`
 +  API allowing administrator users to retrieve information about a user based
 +  on their provider identity (for example, a username). Requires any edition
 +  of the Realm Object Server 1.8.2 or later.
 +
 +### Bugfixes
 +
 +* Realm no longer throws an "unsupported instruction" exception in some cases
 +  when opening a synced Realm asynchronously.
 +
 +3.0.0-beta Release notes (2017-07-14)
 +=============================================================
 +
 +### Breaking Changes
 +
 +* Synchronized Realms require a server running Realm Object Server v2.0 or higher.
 +
 +### Enhancements
 +
 +* Add a new error code to denote 'permission denied' errors when working
 +  with synchronized Realms, as well as an accompanying block that can be
 +  called to inform the binding that the offending Realm's files should be
 +  deleted immediately. This allows recovering from 'permission denied'
 +  errors in a more robust manner. See the documentation for
 +  `RLMSyncErrorPermissionDeniedError` for more information.
 +* Add `-[RLMSyncPermissionValue initWithRealmPath:username:accessLevel:]`
 +  API allowing permissions to be applied to a user based on their username
 +  (usually, an email address). Requires any edition of the Realm Object
 +  Server 1.6.0 or later.
 +* Improve performance of creating Swift objects which contain at least one List
 +  property.
 +
 +### Bugfixes
 +
 +* `List.description` now reports the correct types for nested lists.
 +* Fix unmanaged object initialization when a nested property type returned
 +  `false` from `Object.shouldIncludeInDefaultSchema()`.
 +* Don't clear RLMArrays on self-assignment.
+ 2.10.1 Release notes (2017-09-14)
+ =============================================================
+ 
+ Swift binaries are now produced for Swift 3.0, 3.0.1, 3.0.2, 3.1, 3.2 and 4.0.
+ 
+ ### Enhancements
+ 
+ * Auxiliary files are excluded from backup by default.
+ 
+ ### Bugfixes
+ 
+ * Fix more cases where assigning an RLMArray property to itself would clear the
+   RLMArray.
  
  2.10.0 Release notes (2017-08-21)
  =============================================================
diff --cc Realm.xcodeproj/project.pbxproj
index 456fde88c,11c8c2012..0e193868a
--- a/Realm.xcodeproj/project.pbxproj
+++ b/Realm.xcodeproj/project.pbxproj
@@@ -1085,14 -1107,12 +1089,14 @@@
  		1AD3870E1D4A827C00479110 /* Private */ = {
  			isa = PBXGroup;
  			children = (
+ 				1A6921D11D779774004C3232 /* RLMJSONModels.h */,
+ 				1A6921D21D779774004C3232 /* RLMJSONModels.m */,
  				1AF7EA991D340E700001A9B5 /* RLMNetworkClient.h */,
  				1AF7EA9A1D340E700001A9B5 /* RLMNetworkClient.mm */,
 +				1AD6E79E1E8C217000D4C8B4 /* RLMSyncPermissionResults.h */,
 +				1AD6E79F1E8C217000D4C8B4 /* RLMSyncPermissionResults.mm */,
  				1A33C42C1DAEE445001E87AA /* RLMSyncSessionRefreshHandle.hpp */,
  				1A33C42D1DAEE445001E87AA /* RLMSyncSessionRefreshHandle.mm */,
- 				1A6921D11D779774004C3232 /* RLMJSONModels.h */,
- 				1A6921D21D779774004C3232 /* RLMJSONModels.m */,
  			);
  			name = Private;
  			sourceTree = "<group>";
diff --cc Realm/RLMCollection.mm
index 5ebf49c8e,165177dbd..7e8d7b171
--- a/Realm/RLMCollection.mm
+++ b/Realm/RLMCollection.mm
@@@ -173,26 -175,36 +175,36 @@@ NSArray *RLMCollectionValueForKey(Colle
          return @[];
      }
  
-     RLMRealm *realm = collection.realm;
-     RLMClassInfo *info = collection.objectInfo;
- 
-     NSMutableArray *results = [NSMutableArray arrayWithCapacity:count];
+     NSMutableArray *array = [NSMutableArray arrayWithCapacity:count];
      if ([key isEqualToString:@"self"]) {
-         for (size_t i = 0; i < count; i++) {
-             size_t rowIndex = [collection indexInSource:i];
-             [results addObject:RLMCreateObjectAccessor(realm, *info, rowIndex) ?: NSNull.null];
+         RLMAccessorContext context(realm, info);
+         for (size_t i = 0; i < count; ++i) {
+             [array addObject:collection.get(context, i) ?: NSNull.null];
          }
-         return results;
+         return array;
      }
  
-     for (RLMProperty *prop in info->rlmObjectSchema.swiftGenericProperties) {
-         if ([prop.name isEqual:key] && !prop.optional) {
-             for (size_t i = 0; i < count; i++) {
-                 size_t rowIndex = [collection indexInSource:i];
-                 RLMObjectBase *accessor = RLMCreateObjectAccessor(realm, *info, rowIndex);
-                 [results addObject:[accessor valueForKey:key] ?: NSNull.null];
+     RLMObject *accessor = RLMCreateManagedAccessor(info.rlmObjectSchema.accessorClass, realm, &info);
+ 
+     // List properties need to be handled specially since we need to create a
+     // new List each time
+     if (info.rlmObjectSchema.isSwiftClass) {
+         auto prop = info.rlmObjectSchema[key];
 -        if (prop && prop.type == RLMPropertyTypeArray && prop.swiftIvar) {
++        if (prop && prop.array && prop.type == RLMPropertyTypeObject && prop.swiftIvar) {
+             // Grab the actual class for the generic List from an instance of it
+             // so that we can make instances of the List without creating a new
+             // object accessor each time
+             Class cls = [object_getIvar(accessor, prop.swiftIvar) class];
+             for (size_t i = 0; i < count; ++i) {
+                 RLMListBase *list = [[cls alloc] init];
+                 list._rlmArray = [[RLMManagedArray alloc] initWithList:realm::List(realm->_realm, *info.table(),
+                                                                                    info.tableColumn(prop),
+                                                                                    collection.get(i).get_index())
+                                                                  realm:realm parentInfo:&info
+                                                               property:prop];
+                 [array addObject:list];
              }
-             return results;
+             return array;
          }
      }
  
diff --cc Realm/RLMRealm.mm
index b3c4d067a,aa5d9cf78..e046cc671
--- a/Realm/RLMRealm.mm
+++ b/Realm/RLMRealm.mm
@@@ -66,8 -66,12 +66,12 @@@ void RLMDisableSyncToDisk() 
      realm::disable_sync_to_disk();
  }
  
+ static void RLMAddSkipBackupAttributeToItemAtPath(std::string const& path) {
+     [[NSURL fileURLWithPath:@(path.c_str())] setResourceValue:@YES forKey:NSURLIsExcludedFromBackupKey error:nil];
+ }
+ 
  @implementation RLMRealmNotificationToken
 -- (void)stop {
 +- (void)invalidate {
      [_realm verifyThread];
      [_realm.notificationHandlers removeObject:self];
      _realm = nil;
diff --cc Realm/RLMResults.mm
index 861c0ae8a,a73e42b51..18ee63111
--- a/Realm/RLMResults.mm
+++ b/Realm/RLMResults.mm
@@@ -239,8 -245,8 +239,8 @@@ static inline void RLMResultsValidateIn
  }
  
  - (id)valueForKey:(NSString *)key {
 -    return translateErrors([&] {
 +    return translateRLMResultsErrors([&] {
-         return RLMCollectionValueForKey(self, key);
+         return RLMCollectionValueForKey(_results, key, _realm, *_info);
      });
  }
  
@@@ -273,8 -281,8 +275,8 @@@
  
  - (NSArray *)_unionOfObjectsForKeyPath:(NSString *)keyPath {
      assertKeyPathIsNotNested(keyPath);
 -    return translateErrors([&] {
 +    return translateRLMResultsErrors([&] {
-         return RLMCollectionValueForKey(self, keyPath);
+         return RLMCollectionValueForKey(_results, keyPath, _realm, *_info);
      });
  }
  
@@@ -288,12 -296,12 +290,12 @@@
          @throw RLMException(@"self is not a valid key-path for a KVC array collection operator as 'unionOfArrays'.");
      }
  
 -    return translateErrors([&] {
 +    return translateRLMResultsErrors([&] {
-         NSArray *nestedResults = RLMCollectionValueForKey(self, keyPath);
-         NSMutableArray *flatArray = [NSMutableArray arrayWithCapacity:nestedResults.count];
-         for (id<RLMFastEnumerable> array in nestedResults) {
-             NSArray *nsArray = RLMCollectionValueForKey(array, @"self");
-             [flatArray addObjectsFromArray:nsArray];
+         NSMutableArray *flatArray = [NSMutableArray new];
+         for (id<NSFastEnumeration> array in RLMCollectionValueForKey(_results, keyPath, _realm, *_info)) {
+             for (id value in array) {
+                 [flatArray addObject:value];
+             }
          }
          return flatArray;
      });
@@@ -352,11 -364,8 +354,8 @@@
          return returnNilForEmpty ? nil : @0;
      }
      size_t column = _info->tableColumn(property);
 -    auto value = translateErrors([&] { return (_results.*method)(column); }, methodName);
 +    auto value = translateRLMResultsErrors([&] { return (_results.*method)(column); }, methodName);
-     if (!value) {
-         return nil;
-     }
-     return RLMMixedToObjc(*value);
+     return value ? RLMMixedToObjc(*value) : nil;
  }
  
  - (id)minOfProperty:(NSString *)property {
@@@ -372,7 -384,12 +374,12 @@@
  }
  
  - (id)averageOfProperty:(NSString *)property {
-     return [self aggregate:property method:&Results::average methodName:@"averageOfProperty" returnNilForEmpty:YES];
+     if (_results.get_mode() == Results::Mode::Empty) {
+         return nil;
+     }
+     size_t column = _info->tableColumn(property);
 -    auto value = translateErrors([&] { return _results.average(column); }, @"averageOfProperty");
++    auto value = translateRLMResultsErrors([&] { return _results.average(column); }, @"averageOfProperty");
+     return value ? @(*value) : nil;
  }
  
  - (void)deleteObjectsFromRealm {
@@@ -391,12 -408,8 +398,8 @@@
      return RLMDescriptionWithMaxDepth(@"RLMResults", self, RLMDescriptionMaxDepth);
  }
  
- - (NSUInteger)indexInSource:(NSUInteger)index {
-     return translateRLMResultsErrors([&] { return _results.get(index).get_index(); });
- }
- 
  - (realm::TableView)tableView {
 -    return translateErrors([&] { return _results.get_tableview(); });
 +    return translateRLMResultsErrors([&] { return _results.get_tableview(); });
  }
  
  - (RLMFastEnumerator *)fastEnumerator {
diff --cc build.sh
index 3d50af4c1,5a66004ff..7ef747cca
--- a/build.sh
+++ b/build.sh
@@@ -629,9 -647,16 +639,11 @@@ case "$COMMAND" i
          exit 0
          ;;
  
 -    "test-ios7-static")
 -        test_ios_static "name=iPhone 5S,OS=7.1"
 -        exit 0
 -        ;;
 -
      "test-ios-dynamic")
          xc "-scheme Realm -configuration $CONFIGURATION -sdk iphonesimulator -destination 'name=iPhone 6' build"
-         xc "-scheme Realm -configuration $CONFIGURATION -sdk iphonesimulator -destination 'name=iPhone 6' test 'ARCHS=\$(ARCHS_STANDARD_32_BIT)'"
+         if (( $(xcode_version_major) < 9 )); then
+             xc "-scheme Realm -configuration $CONFIGURATION -sdk iphonesimulator -destination 'name=iPhone 6' test 'ARCHS=\$(ARCHS_STANDARD_32_BIT)'"
+         fi
          xc "-scheme Realm -configuration $CONFIGURATION -sdk iphonesimulator -destination 'name=iPhone 6' test"
          exit 0
          ;;
```

### CODE REVIEW

**Comment by bdash** [comment]
Uuuugh, it looks like this is blocked until we get a working core / sync release that includes realm/realm-core#2823 😞

**Comment by tgoyne** [comment]
The latest core/sync releases include realm/realm-core#2823, although the object server tests will be broken until the PR to adapt to those changes is complete.

**Comment by bdash** [comment]
The only available sync releases that include the fix for realm/realm-core#2823 all suffer from realm/realm-sync#1648, which breaks a number of our builds.

**Comment by bdash** [comment]
This should be ready to go now that `master-3.0` is on updated core / sync versions.

**Pull request merged**
