### PR TITLE
changed name of typealias "User" to "SyncUser"

### PR DESCRIPTION
**Pull request by skydivedan**
Changed the name of the typealias `User` to `SyncUser`, so that it wouldn't cause a collision with other people's `User` classes. This also adopts a similar naming convention used by `SyncManager` and `SyncSession`

### CODE REVIEW

**Comment by skydivedan** [comment]
re: https://github.com/realm/realm-cocoa/issues/4153

**Comment by jpsim** [comment]
@skydivedan thanks for your contribution!

Could you kindly add a changelog entry in the "Breaking changes" section, something along the lines of this?

```md
* rename `User` to `SyncUser` in Realm Swift.
```

**Comment by skydivedan** [comment]
@jpsim - ok, done.

**Comment by bdash** [comment]
I'll be merging this shortly via #4181.

**Pull request closed without merging**
