### PR TITLE
update core to 0.100.2

### LINKED ISSUE #3532: Assertion failed: real_ndx != detached_ref in 0.101.0
## Goals

I want to use RLMLinkingObjects widely.

## Expected Results

I expected to use RLMLinkingObjects safely anytime before deleting the instance that has the RLMLinkingObjects property.

## Actual Results

```
core/include/realm/table_view.hpp:1425: [realm-core-0.100.0] Assertion failed: real_ndx != detached_ref
0   Backlink                            0x000000010022ee04 _ZN5realm4util18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 40
1   Backlink                            0x000000010022f02c _ZN5realm4util9terminateEPKcS2_l + 340
2   Backlink                            0x00000001000d5590 _ZN5realm9TableView3getEm + 204
3   Backlink                            0x00000001000d4cf8 _ZN5realm9TableViewixEm + 28
4   Backlink                            0x00000001000b0c04 _ZN5realm5_impl15ResultsNotifier17calculate_changesEv + 2356
5   Backlink                            0x00000001000b0e48 _ZN5realm5_impl15ResultsNotifier3runEv + 440
6   Backlink                            0x000000010008cfc0 _ZN5realm5_impl16RealmCoordinator19run_async_notifiersEv + 5816
7   Backlink                            0x000000010008b710 _ZN5realm5_impl16RealmCoordinator9on_changeEv + 40
8   Backlink                            0x000000010005d15c _ZN5realm5_impl20ExternalCommitHelper6listenEv + 672
9   Backlink                            0x000000010005dc04 _ZZN5realm5_impl20ExternalCommitHelperC1ERNS0_16RealmCoordinatorEENK3$_0clEv + 24
10  Backlink                            0x000000010005dbe0 _ZNSt3__112__async_funcIZN5realm5_impl20ExternalCommitHelperC1ERNS2_16RealmCoordinatorEE3$_0JEE9__executeIJEEEvNS_15__tuple_indicesIJXspT_EEEE + 64
11  Backlink                            0x000000010005db94 _ZNSt3__112__async_funcIZN5realm5_impl20ExternalCommitHelperC1ERNS2_16RealmCoordinatorEE3$_0JEEclEv + 24
12  Backlink                            0x000000010005daa4 _ZNSt3__119__async_assoc_stateIvNS_12__async_funcIZN5realm5_impl20ExternalCommitHelperC1ERNS3_16RealmCoordinatorEE3$_0JEEEE9__executeEv + 32
13  Backlink                            0x000000010005e328 _ZNSt3__114__thread_proxyINS_5tupleIJMNS_19__async_assoc_stateIvNS_12__async_funcIZN5realm5_impl20ExternalCommitHelperC1ERNS5_16RealmCoordinatorEE3$_0JEEEEEFvvEPSB_EEEEEPvSG_ + 388
14  libsystem_pthread.dylib             0x0000000182fa7b28 <redacted> + 156
15  libsystem_pthread.dylib             0x0000000182fa7a8c <redacted> + 0
16  libsystem_pthread.dylib             0x0000000182fa5028 thread_start + 4
IMPORTANT: if you see this error, please send this log to help@realm.io.
```

image

## Steps to Reproduce

- Make a relationship like as _One-to-Many Relationships_ on https://realm.io/news/realm-objc-swift-0.100.0/
- Read a RLMLinkingObjects property
- Delete the instances that has the property
- Do anything for 10 milliseconds or so without doing anything about the deleted instances.
- Xcode shows 'Assertion failed'

## Code Sample

```
@class Person;

@interface Dog : RLMObject
@property NSString *name;
@property Person *owner;
@end

@implementation Dog
@end

@interface Person : RLMObject
@property NSString *name;
@property (readonly) RLMLinkingObjects<Dog *> *dogs;
@end

@implementation Person
+ (NSDictionary *)linkingObjectsProperties {
    return @{
             @"dogs": [RLMPropertyDescriptor descriptorWithClass:Dog.class propertyName:@"owner"],
             };
}
@end

...

-(void)foo {
    Person *john = [[Person alloc] initWithValue:@[@"John"]];
    Dog *fido = [[Dog alloc] initWithValue:@[@"Fido", john]];

    RLMRealm *realm = [RLMRealm defaultRealm];
    [realm transactionWithBlock:^{
        [realm addObject:fido];
        [realm addObject:john];
    }];

    RLMLinkingObjects *dogsOfJohn = john.dogs;
    NSLog(@"%@", dogsOfJohn);

    [realm transactionWithBlock:^{
        [realm deleteObject:fido];
        [realm deleteObject:john];
    }];

    [NSThread sleepForTimeInterval:0.01];
}
```

## Version of Realm and Tooling

Realm version: 0.101.0.(67499adc2a5da5344d2f60c9069145e08b285612)

Xcode version: 7.3.1

iOS version: 9.3.1

I didn't use any dependency manager for above code. I modified AppDelegate.m of Backlink in examples/ios/objc folder.

### LINKED ISSUE #3536: Realm Crashing constantly in version 0.101.0
## Goals

What do you want to achieve?

Happiness & Peace

## Expected Results

What did you expected to happen?

Get user info from db

## Actual Results

What did happened instead?  
e.g. the stack trace of a crash

```
Realm                                0x000000010159cd5c please_report_this_error_to_help_at_realm_dot_io + 8
4   Realm                                0x000000010159ce50 realm::util::terminate_internal(std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) + 228
5   Realm                                0x00000001014d1e38 void realm::util::terminate<unsigned long, unsigned long>(char const*, char const*, long, unsigned long, unsigned long) (terminate.hpp:63)
6   Realm                                0x00000001015a2b8c realm::Array::set(unsigned long, long long) + 132
7   Realm                                0x00000001016cc5c8 realm::BpTree<realm::util::Optional<long long> >::UpdateHandler::update(realm::MemRef, realm::ArrayParent*, unsigned long, unsigned long) + 112
8   Realm                                0x00000001015a8a98 realm::Array::update_bptree_elem(unsigned long, realm::Array::UpdateHandler&) + 184
9   Realm                                0x00000001016cc508 realm::BpTree<realm::util::Optional<long long> >::set(unsigned long, realm::util::Optional<long long>) + 204
10  Realm                                0x0000000101643b18 realm::TimestampColumn::set(unsigned long, realm::Timestamp const&) + 128
11  Realm                                0x00000001016b1810 realm::Table::set_timestamp(unsigned long, unsigned long, realm::Timestamp) + 272
12  Realm                                0x00000001016b12d0 realm::Table::upgrade_olddatetime() + 384
13  Realm                                0x0000000101645850 realm::Group::upgrade_file_format(int) + 372
14  Realm                                0x000000010164f24c realm::SharedGroup::upgrade_file_format(bool, int) + 100
15  Realm                                0x000000010164e320 realm::SharedGroup::do_open(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, realm::SharedGroup::DurabilityLevel, bool, char const*, bool) + 2716
16  Realm                                0x0000000101588ab4 realm::SharedGroup::SharedGroup(realm::Replication&, realm::SharedGroup::DurabilityLevel, char const*, bool) (group_shared.hpp:817)
17  Realm                                0x0000000101586568 realm::Realm::open_with_config(realm::Realm::Config const&, std::__1::unique_ptr<realm::Replication, std::__1::default_delete<realm::Replication> >&, std::__1::unique_ptr<realm::SharedGroup, std::__1::default_delete<realm::SharedGroup> >&, std::__1::unique_ptr<realm::Group, std::__1::default_delete<realm::Group> >&) (group_shared.hpp:785)
18  Realm                                0x0000000101586284 realm::Realm::Realm(realm::Realm::Config) (shared_realm.cpp:64)
19  Realm                                0x00000001014eb61c std::__1::shared_ptr<realm::Realm> std::__1::shared_ptr<realm::Realm>::make_shared<realm::Realm::Config>(realm::Realm::Config&&) (memory:2185)
20  Realm                                0x00000001014e6490 realm::_impl::RealmCoordinator::get_realm(realm::Realm::Config) (memory:4749)
21  Realm                                0x00000001015876e0 realm::Realm::get_shared_realm(realm::Realm::Config) (shared_realm.cpp:181)
22  Realm                                0x00000001015769e0 +[RLMRealm openSharedRealm:error:] (RLMRealm.mm:285)
23  Realm                                0x0000000101576da0 +[RLMRealm realmWithConfiguration:error:] (RLMRealm.mm:356)
24  RealmSwift                           0x0000000102880af0 RealmSwift.Realm.__allocating_init  throws (configuration : RealmSwift.Realm.Configuration) (Realm.swift:0)
25  Resoltz                              0x0000000100086f88 static Resoltz.UsersRepository.loadUser ((succeeded : Swift.Bool) -> ())() (UsersRepository.swift:43)
26  Resoltz                              0x0000000100067dd4 @objc Resoltz.LoadingViewController.viewDidAppear (Swift.Bool)() (LoadingViewController.swift:42)
```

## Steps to Reproduce

What are steps we can follow to reproduce this issue?

The same build is installed on multiple devices,  only 1 of my testers is facing this issue and she's in LA so I don't have access to her phone.

## Code Sample

Provide a code sample or test case that highlights the issue.
If relevant, include your model definitions.
For larger code samples, links to external gists/repositories are preferred.
Alternatively share confidentially via mail to help@realm.io.
Full Xcode projects that we can compile ourselves are ideal!

```swift
 class func loadUser(completed: (succeeded: Bool) -> ()) {
    do {
      let realm = try Realm()
      
      let users = realm.objects(User)
      
      if !users.isEmpty {
        completed(succeeded: true)
        
        UsersRepository.refereshUser(users[0].id, completed: { _ in
        })
      }
      else {
        completed(succeeded: false)
      }
    } catch let error as NSError {
      Log.trackError(error)
      
      completed(succeeded: false)
    }
  }
```

## Version of Realm and Tooling

[In the CONTRIBUTING guidelines](https://git.io/vgxJO), you will find a script,
which will help determining these versions.

Realm version: 0.101.0
Xcode version: 7.3.1

iOS/OSX version: 9.3.1

Dependency manager + version: ?

### PR DESCRIPTION
**Pull request by jpsim**
/cc @tgoyne @bdash 

Fixes #3532. Fixes #3536.

### CODE REVIEW

**Comment by jpsim** [comment]
Fixes #3532.

**Comment by jpsim** [comment]
Also fixes #3536.

**Comment by bdash** [comment]
👍

**Comment by tgoyne** [comment]
iOS device tests are consistently failing. Looking into what the problem could be.

**Comment by tgoyne** [comment]
Device tests work for me locally on both 32-bit and 64-bit devices and worked on CI after restarting the device, so the failures appear to just be more of the previous flakiness as opposed to anything related to this PR.

**Pull request merged**
