### PR TITLE
[RLMMigration] Call enumeration blocks inside an autoreleasepool

### LINKED ISSUE #2205: Enumeration of objects in migration without loading everything into memory
Hi.

I've made a custom keyboard for iOS using realm for the dictionaries.
A dictionary contains up to 400.000 words, and I'm unable to do migrations from the keyboard extension due to the extensions being limited at 50mb memory usage.

Would it be possible to allow for enumeration of objects either per object or in batches in a migration without loading the whole db into memory? (as an example a 9.8mb realm file with 360.000 words peaks at 152mb if i enumerate (making no changes) during migration)

If there is any way to get this done currently i would also love to know.

Thanks
Rasmus.

### PR DESCRIPTION
**Pull request by segiddins**
Closes #2205.

\c @tgoyne

### CODE REVIEW

**Comment by tgoyne** [comment]
changelog

**Comment by segiddins** [comment]
changelog added

**Comment by tgoyne** [comment]
:+1:

**Comment by porsager** [comment]
Hi @segiddins 

Cool - that's some very fast action right there ! :)

I use swift 2.0, so i tried merging this branch with the swift-2.0 branch and run the same migration with it. It goes to about 80mb of memory usage and then just freezes there forever. 

I don't know if it's of any help, but if i pause in the debugger the stack looks like this: 

#0	0x0399154a in __psynch_mutexwait ()
#1	0x03958210 in _pthread_mutex_lock ()
#2	0x03958003 in pthread_mutex_lock ()
#3	0x003fea61 in realm::util::RobustMutex::low_level_lock() ()
#4	0x004aa3d3 in realm::SharedGroup::do_begin_write() ()
#5	0x004aa297 in realm::SharedGroup::begin_write() ()
#6	0x003c54cb in realm::SharedGroup::upgrade_file_format()

Thanks for the very quick reaction!

**Comment by segiddins** [comment]
@porsager that's probably a different issue -- can you share a project that demonstrates that problem with us?

**Comment by segiddins** [comment]
Test failures appear unrelated?

**Comment by jpsim** [comment]
@segiddins please rebase this

**Comment by segiddins** [comment]
Rebased

**Comment by porsager** [comment]
@segiddins You are right it is independent of this issue. Would you want me to create a new issue for it, or can i email you a test project with the issue?

**Comment by segiddins** [comment]
@porsager an email with a test project would be perfect, thanks!

**Comment by jpsim** [comment]
:+1:

**Pull request merged**
