### PR TITLE
Update to core 0.95.4

### LINKED ISSUE #2740: Assertion failure in realm::SlabAlloc::attach_file
Crash on device when attempting to create in-memory Realm after upgrading to 0.96.0.  iOS 9.0, iPhone 5s

```
ProductName:	Mac OS X
ProductVersion:	10.11
BuildVersion:	15A284

/Applications/Xcode.app/Contents/Developer
Xcode 7.1
Build version 7B91b
/usr/local/bin/pod
0.39.0
Realm (0.96.0)
/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
/usr/bin/git
git version 2.4.9 (Apple Git-60)
```

```
Thread : Crashed: Realm
0  libsystem_kernel.dylib         0x000000019b6331e0 __pthread_kill + 8
1  libsystem_pthread.dylib        0x000000019b6fcf0c pthread_kill + 112
2  libsystem_c.dylib              0x000000019b5a6b78 abort + 140
3  myApp                           0x000000010088efec realm::util::terminate_internal(std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) + 404
4  myApp                           0x000000010088f128 realm::util::terminate_internal(std::__1::basic_stringstream<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) + 720
5  libsystem_pthread.dylib        0x000000019b6fcf0c pthread_kill + 112
6  myApp                           0x000000010098442c void realm::util::terminate<bool, bool>(char const*, char const*, long, bool, bool) + 428
7  libsystem_pthread.dylib        0x000000019b6fcf0c pthread_kill + 112
8  myApp                           0x0000000100891228 realm::SlabAlloc::attach_file(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, realm::SlabAlloc::Config&) + 7960
9  myApp                           0x0000000100925c78 realm::SharedGroup::do_open_2(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, realm::SharedGroup::DurabilityLevel, bool, char const*) + 1972
10 myApp                           0x000000010092586c realm::SharedGroup::do_open_1(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, realm::SharedGroup::DurabilityLevel, bool, char const*, bool) + 936
11 myApp                           0x000000010087b780 realm::SharedGroup::SharedGroup(realm::Replication&, realm::SharedGroup::DurabilityLevel, char const*, bool) (group_shared.hpp:786)
12 myApp                           0x00000001008767a4 -[RLMRealm initWithPath:key:readOnly:inMemory:dynamic:error:] (RLMRealm.mm:240)
13 myApp                           0x000000010087755c +[RLMRealm realmWithConfiguration:error:] (RLMRealm.mm:401)
14 myApp                           0x00000001001ca1a4 +[MyAppModelManager inMemoryRealmWithName:] (MyAppModelManager.m:22)
15 myApp                           0x000000010019a138 __34-[MyAppDataSource processResponse:]_block_invoke (MyAppDataSource.m:113)
16 libdispatch.dylib              0x000000019b4e57b0 _dispatch_call_block_and_release + 24
17 libdispatch.dylib              0x000000019b4e5770 _dispatch_client_callout + 16
18 libdispatch.dylib              0x000000019b4f175c _dispatch_queue_drain + 864
19 libdispatch.dylib              0x000000019b4e9274 _dispatch_queue_invoke + 464
20 libdispatch.dylib              0x000000019b4e5770 _dispatch_client_callout + 16
21 libdispatch.dylib              0x000000019b4f3bb0 _dispatch_root_queue_drain + 2140
22 libdispatch.dylib              0x000000019b4f334c _dispatch_worker_thread3 + 112
23 libsystem_pthread.dylib        0x000000019b6f9478 _pthread_wqthread + 1092
24 libsystem_pthread.dylib        0x000000019b6f9028 start_wqthread + 4
```

### LINKED ISSUE #2841: Exception from SlabAlloc class
Hi,

I am using realm version 0.96.2 in my app. Everything was working fine but app crashed just once with the below stacktrace. I restarted the app and everything is fine since then. 

Any idea what could be reason behind this error?

Gaurav

```
alloc_slab.cpp:494: [realm-core-0.94.0] Assertion failed: cfg.session_initiator || !cfg.is_shared [0, 0]
0   Realm                               0x0000000101e86338 _ZN5realm4util18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 44
1   Realm                               0x0000000101f98d20 _ZN5realm4util9terminateIbJbEEEvPKcS3_lT_DpT0_ + 428
2   Realm                               0x0000000101e88a6c _ZN5realm9SlabAlloc11attach_fileERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERNS0_6ConfigE + 2396
3   Realm                               0x0000000101f24df4 _ZN5realm11SharedGroup9do_open_2ERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEbNS0_15DurabilityLevelEbPKc + 796
4   Realm                               0x0000000101f249e8 _ZN5realm11SharedGroup9do_open_1ERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEbNS0_15DurabilityLevelEbPKcb + 28
5   Realm                               0x0000000101e658b0 _ZN5realm11SharedGroup4openERNS_11ReplicationENS0_15DurabilityLevelEPKcb + 168
6   Realm                               0x0000000101e655e4 _ZN5realm11SharedGroupC2ERNS_11ReplicationENS0_15DurabilityLevelEPKcb + 632
7   Realm                               0x0000000101e65354 _ZN5realm11SharedGroupC1ERNS_11ReplicationENS0_15DurabilityLevelEPKcb + 64
8   Realm                               0x0000000101e5ba24 -[RLMRealm initWithPath:key:readOnly:inMemory:dynamic:error:] + 2756
9   Realm                               0x0000000101e5d5b0 +[RLMRealm realmWithConfiguration:error:] + 1356
10  RealmSwift                          0x00000001022141f8 _TTOFCSo8RLMRealmCfMS_FzT13configurationCSo21RLMRealmConfiguration_S_ + 108
11  RealmSwift                          0x0000000102210e90 _TFC10RealmSwift5RealmcfMS0_FzT13configurationVS0_13Configuration_S0_ + 360
12  RealmSwift                          0x00000001022111c4 _TFC10RealmSwift5RealmCfMS0_FzT13configurationVS0_13Configuration_S0_ + 420
...
...
...
29  UIKit                               0x000000018a9a4a04 <redacted> + 1080
30  UIKit                               0x000000018abc417c <redacted> + 2536
31  UIKit                               0x000000018abc0f50 <redacted> + 168
32  FrontBoardServices                  0x000000018f1a77c4 <redacted> + 184
33  FrontBoardServices                  0x000000018f1a7b44 <redacted> + 56
34  CoreFoundation                      0x0000000185340544 <redacted> + 24
35  CoreFoundation                      0x000000018533ffd8 <redacted> + 540
36  CoreFoundation                      0x000000018533dcd8 <redacted> + 724
37  CoreFoundation                      0x000000018526cca0 CFRunLoopRunSpecific + 384
38  UIKit                               0x000000018a98a1c8 <redacted> + 460ok
39  UIKit                               0x000000018a984ffc UIApplicationMain + 204
...
41  libdyld.dylib                       0x000000019a78a8b8 <redacted> + 4
IMPORTANT: if you see this error, please send this log to help@realm.io.
```

### LINKED ISSUE #2913: Realm crash(EXC_BAD_ACCESS KERN_PROTECTION_FAILURE) upon force closing app
Hello,

We just launched a test version of our app in the appstore and are receiving lots of crashreports through crashlytics. We managed to reproduce this crash through force killing the app. The actual networking task is already done, so there should be no reason for this crash to occure.

The app crashes with the following stacktrace:

```
Thread : Crashed: com.apple.main-thread
0  Realm                          0x10120622c realm::_impl::WriteLogCollector::do_prepare_commit(realm::SharedGroup&, unsigned long long) + 372
1  Realm                          0x10117edf8 realm::SharedGroup::do_commit() + 80
2  Realm                          0x1010cbc64 realm::SharedGroup::commit_and_continue_as_read() + 60
3  Realm                          0x1010c93cc -[RLMRealm commitWriteTransaction:] + 100
4  Realm                          0x1010c9570 -[RLMRealm transactionWithBlock:error:] + 100
5  RealmSwift                     0x1013bac84 _TFC10RealmSwift5Realm5writefS0_FzFT_T_T_ + 140
-----
8  AFNetworking                   0x100d57dc8 __84-[AFHTTPSessionManager dataTaskWithHTTPMethod:URLString:parameters:success:failure:]_block_invoke74 + 116
9  AFNetworking                   0x100d6b8f4 __72-[AFURLSessionManagerTaskDelegate URLSession:task:didCompleteWithError:]_block_invoke_271 + 144
10 libdispatch.dylib              0x1977e56e8 _dispatch_call_block_and_release + 24
11 libdispatch.dylib              0x1977e56a8 _dispatch_client_callout + 16
12 libdispatch.dylib              0x1977eadb0 _dispatch_main_queue_callback_4CF + 1844
13 CoreFoundation                 0x1824bc1f8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
14 CoreFoundation                 0x1824ba060 __CFRunLoopRun + 1628
15 CoreFoundation                 0x1823e8ca0 CFRunLoopRunSpecific + 384
16 GraphicsServices               0x18d624088 GSEventRunModal + 180
17 UIKit                          0x187b00ffc UIApplicationMain + 204
18 OSM                            0x1001839cc main (AppDelegate.swift:15)
19 libdyld.dylib                  0x1978168b8 start + 4
```

### PR DESCRIPTION
**Pull request by tgoyne**
Fixes #2740. Fixes #2913. Fixes #2841.

### CODE REVIEW

**Comment by bdash** [comment]
:+1:

**Comment by tgoyne** [comment]
I think this fixes https://github.com/realm/realm-cocoa/issues/2740. Any others?

**Comment by bdash** [comment]
It looks like it may also fix #291 and #2841.

**Comment by jpsim** [comment]
I think you meant #2910 @bdash, and no other GH issues tracking this in cocoa I believe. :+1:

**Comment by bdash** [comment]
I meant #2913.

**Pull request merged**
