### PR TITLE
Fix warnings seen when building with Xcode 9.3

### PR DESCRIPTION
**Pull request by bdash**

### CODE REVIEW

**Comment by tgoyne** [comment]
I'm not particularly a fan of riddling self-> all over the place rather than just disabling the warning.

**Comment by bdash** [comment]
It was only a small number of places, so it seemed easier to just go with it than worry about disabling the warning.

**Comment by bdash** [comment]
The CI failures are due to a Jenkins upgrade that appears to have broken a plug-in our PR job relies on. Since this change could easily introduce problems for older Xcode versions, I'd like to see CI succeed before we merge this.

**Comment by bdash** [comment]
I disabled the warning that otherwise required inserting `self->`.

**Pull request merged**
