### PR TITLE
[RLMCollection] Ensure swift list accessors are initialized

### LINKED ISSUE #1876: List accessors aren't properly initialized in Swift fast enumeration
hi guys ,i'm using RealmSwift 0.92
i have a class
```swift
class MediaSentenceWord: Object {
   let librarywords = List<LibraryWord>()
}
```
```
var results = realm.objects(MediaSentenceWord)
for i in 0...results.count-1{
       println(libResults[i].librarywords.count) // every thing ok
}
```
but if i write this ,there is a problem:
```
for item in results{
        println(item.librarywords.count) // always 0  !!!!!
}
```

### PR DESCRIPTION
**Pull request by segiddins**
Closes #1876.
Alternative to #1878.

\c @kishikawakatsumi @tgoyne

### CODE REVIEW

**Comment by tgoyne** [comment]
This is a significant performance regression for obj-c.

**Comment by segiddins** [comment]
> This is a significant performance regression for obj-c.

I thought you might say that.... I have another idea, let me try it out.

**Comment by segiddins** [comment]
I can't reproduce those test failures locally...

**Comment by segiddins** [comment]
Updated, this should work now

**Comment by tgoyne** [comment]
:+1:

**Comment by kishikawakatsumi** [comment]
:+1:

**Pull request merged**
