### PR TITLE
Add missing Error cases into switch case

### PR DESCRIPTION
**Pull request by RafaelPlantard**
To avoid Xcode warnings around it.

### CODE REVIEW

**Comment by jpsim** [comment]
@RafaelPlantard thanks for the effort, but this has already been addressed in `realm/realm-object-store@master`, so the right way to address this would be to update the submodule to point to the head of that branch.

**Comment by RafaelPlantard** [comment]
Thanks for the tip @jpsim, but how can I update the Realm submodule when using CocoaPods?

**Comment by jpsim** [comment]
You could point CocoaPods to a branch of this repo that includes those updates to the object store submodule, such as #4219:

```ruby
pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'az/refactor-sync-os', submodules: true
pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'az/refactor-sync-os', submodules: true
```

**Comment by RafaelPlantard** [comment]
Thanks @jpsim...

**Pull request closed without merging**
