### PR TITLE
Guarantee 64 bit integer precision for dates even on 32-bit

### PR DESCRIPTION
**Pull request by segiddins**
See https://github.com/realm/realm-cocoa/pull/2154.
Closes https://github.com/realm/realm-cocoa/issues/2152.

\c @tgoyne @bdash

### CODE REVIEW

**Comment by segiddins** [comment]
retest this pelase

**Comment by segiddins** [comment]
retest this please

**Comment by segiddins** [comment]
failures appear to be unrelated

**Comment by jpsim** [comment]
Needs a changelog entry. Otherwise looks good.

**Comment by segiddins** [comment]
CHANGELOG added

**Comment by segiddins** [comment]
Rebased

**Pull request merged**
