### PR TITLE
Fix for deleting objects from the wrong realm

### PR DESCRIPTION
**Pull request by alazier**
@segiddins @tgoyne 

Cherry-picked/merge from swift-realm branch.

### CODE REVIEW

**Comment by segiddins** [comment]
:+1:, but mostly because I wrote that :)

**Comment by tgoyne** [comment]
`RLMArray` and `RLMResults` appear to also have the same behavior of when passing them to a different realm's `deleteObjects:`.

**Comment by segiddins** [comment]
> RLMArray and RLMResults appear to also have the same behavior of when passing them to a different realm's deleteObjects:.

Addressed

**Comment by alazier** [comment]
doesn't look like we are testing either the RLMArray or RLMResults cases.

**Comment by segiddins** [comment]
Tests added

**Comment by alazier** [comment]
:+1:

**Comment by tgoyne** [comment]
:+1:

**Pull request merged**
