### PR TITLE
Remove unused variable

### PR DESCRIPTION
**Pull request by cltnschlosser**

### CODE REVIEW

**Review by jsflax — APPROVED** [review]
Nice change, it was a pesky warning.

**Comment by jsflax** [comment]
Before merging this, could you please sign our CLA? https://docs.google.com/forms/d/e/1FAIpQLSeQ9ROFaTu9pyrmPhXc-dEnLD84DbLuT_-tPNZDOL9J10tOKQ/viewform

**Comment by cltnschlosser** [comment]
> Before merging this, could you please sign our CLA? https://docs.google.com/forms/d/e/1FAIpQLSeQ9ROFaTu9pyrmPhXc-dEnLD84DbLuT_-tPNZDOL9J10tOKQ/viewform

Done

**Comment by cltnschlosser** [comment]
@jsflax Any idea what's wrong with CI? Also, I'll need someone else to click merge when the time comes.

**Comment by jsflax** [comment]
There's a number of issues with the CI at the moment– some blocked due to issues with our external dependencies, others due to undiagnosed testing issues.

We've a CI overhaul project scheduled to begin Soon, so it'll be addressed then.

In the meantime, I can merge this whenever you're ready.

**Comment by cltnschlosser** [comment]
> There's a number of issues with the CI at the moment– some blocked due to issues with our external dependencies, others due to undiagnosed testing issues.
> 
> We've a CI overhaul project scheduled to begin Soon, so it'll be addressed then.
> 
> In the meantime, I can merge this whenever you're ready.

Yeah, merge whenever!

**Pull request merged**
