### PR TITLE
create separate module for private dependencies used by RLMSupport.swift

### PR DESCRIPTION
**Pull request by alazier**
@segiddins

### CODE REVIEW

**Comment by segiddins** [comment]
Let's rename `RLMArray_Private.h` and add documentation to the one method in it?

**Comment by alazier** [comment]
I think this is fine the way it is for now. Not worth further effort at this point.

**Comment by segiddins** [comment]
With this change, you'll have to `import Realm.SwiftSupport` everywhere you want to use `RLMArray(objectClassName:)`

**Comment by alazier** [comment]
That shouldn't be the case - at least it wasn't when just using the Realm.Private module.

**Pull request closed without merging**
