### PR TITLE
Expose distinct query via ObjC and Swift APIs

### PR DESCRIPTION
**Pull request by qubblr**
First I'd like to thank you guys for all the incredible work you are doing!

Ability to get distinct and sorted data is vital to my new project. According to [this PR](https://github.com/realm/realm-object-store/pull/467) the object store is ready so I followed @jpsim's [suggestion](https://github.com/realm/realm-cocoa/issues/1103#issuecomment-287484504) and exposed it via a new method on Results.

Hope this helps.

To do:
- [ ] tests
- [ ] documentation

### CODE REVIEW

**Comment by jpsim** [comment]
Thanks for the PR and your interest in doing this @qubblr! I've marked this as "in-progress" until you address the tests and documentation items you mentioned. We might want to bikeshed on the naming a bit too, but what you have seems like a good starting point. We'll definitely want to refer to "key paths" and not "properties" though, since we moved our terminology to that a few months ago.

And if the object store implementation doesn't yet support nested key paths (it doesn't _appear_ to at quick glance) we'll need to update that as well.

**Comment by bdash** [comment]
> And if the object store implementation doesn't yet support nested key paths (it doesn't appear to at quick glance) we'll need to update that as well.

It should, AFAICT, since it takes a `DistinctDescriptor`, which [contains a vector of column indexes](https://github.com/realm/realm-core/blob/develop/src/realm/views.hpp#L48-L54).

**Comment by ppaulojr** [comment]
@qubblr I have interest in this feature as well. If you want I can help with tests and docs. Let me know.

**Comment by bdash** [comment]
This was closed automatically due to my merging of `master-3.0` into `master`. Reopening.

**Comment by FreudGit** [comment]
@bdash May I please ask what are the status.  Do we not have a way to filter distinct() ?  Thanks

**Comment by gcox** [comment]
Can we go ahead and close this since it's handled in #5467

**Pull request closed without merging**
