### PR TITLE
moving from iCloud to CloudKit

### PR DESCRIPTION
**Pull request by vinnyt**
addressing issues #4415

instances of iCloud renamed to CloudKit.

### CODE REVIEW

**Comment by jpsim** [comment]
Thanks @vinnyt! I'll add some changelog entries for this and #4362 in an upcoming PR.

**Comment by jpsim** [comment]
Changelog entries added in f495a37.

**Comment by vinnyt** [comment]
@jpsim sorry about not getting the changelog entry.  Thank you for doing that.

**Comment by jpsim** [comment]
No problem at all! It's nice to see contributions from users, I hope you keep it up!

**Pull request merged**
