### PR TITLE
[Podspec] Enable WMO for RealmSwift

### PR DESCRIPTION
**Pull request by segiddins**
This require CocoaPods 0.38, but should fix releasability.

\c @jpsim @mrackwitz

### CODE REVIEW

**Comment by tgoyne** [comment]
While this is probably a good change, I don't see how it could fix any problems other than by coincidence.

**Comment by jpsim** [comment]
I think this warrants a changelog entry, even though we haven't done that in the past for installation-related changes.

**Comment by segiddins** [comment]
CHANGELOG added

**Comment by jpsim** [comment]
:+1:

**Pull request merged**
