### PR TITLE
Update to core version 0.88.0

### PR DESCRIPTION
**Pull request by tgoyne**

### CODE REVIEW

**Comment by semireg** [comment]
(y)

**Comment by alazier** [comment]
:+1:

**Comment by jpsim** [comment]
Shouldn't we also add "Add support for comparing string columns to other string columns in queries." to our changelog? That was included in core 0.88.0.

**Comment by tgoyne** [comment]
No, I still need to expose it in the binding.

**Comment by jpsim** [comment]
Right, thanks.

**Comment by jpsim** [comment]
Looks like https://github.com/realm/realm-core/pull/639 was never reflected in core's release notes, but it was included in 0.87.5. We should add something like "Fixed issue where querying for non-null relationships would return incomplete results.".

**Pull request merged**
