### PR TITLE
Update to Core 0.91.1

### PR DESCRIPTION
**Pull request by segiddins**

### CODE REVIEW

**Comment by tgoyne** [comment]
Needs changelog entries for the core changes.

**Comment by segiddins** [comment]
@tgoyne added the one bug fix

**Comment by tgoyne** [comment]
Looking into the perf regression as it appears to be real.

**Comment by tgoyne** [comment]
Perf regression will be fixed by https://github.com/realm/realm-core/pull/931.

**Comment by tgoyne** [comment]
No new changelog entries needed for 0.91.1 as it's just fixing regressions in 0.91.0.

**Comment by segiddins** [comment]
retest this please

**Pull request merged**
