### PR TITLE
When a type error is rasied, include information about the problemati…

### LINKED ISSUE #1827: Better crash logging caused by invalid fields
Hi guys!
Thanks again for your great work.

I have a small issue. 
We got a crash report, with the following exception:
`Terminating app due to uncaught exception 'Invalid value', reason: 'object must be of type string'`

Usually when this happens while developing, we put some breakpoints in the Realm pod and see what key failed.
In this case we cannot do this.
Can you guys give the log some more information? What was the field, what was the value? The more the better...
What do you think?

### PR DESCRIPTION
**Pull request by bdash**
…c object in the exception.

Fixes #1827.

/cc @jpsim

### CODE REVIEW

**Comment by jpsim** [comment]
There's more useful information we could add in there: "Expected object of type Employee for property employees, but received: <Person 0xdeadbeef>". And actually, wouldn't it make more sense to print the type of the value rather than the value itself?

**Comment by bdash** [comment]
It's possible to print only the value's class, but the value itself seems like it could be useful information.

**Comment by segiddins** [comment]
All of the values should be printed in single quotes.

**Comment by segiddins** [comment]
:+1:

**Comment by tgoyne** [comment]
:+1: 

changelog

**Pull request merged**
