### PR TITLE
[RLMProperty] Fail gracefully when `get<Key>` is defined for array properties

### PR DESCRIPTION
**Pull request by mrackwitz**
Makes it easier to figure out what's wrong in scenarios like described in #2720.
* [ ] Test
* [ ] Actual assert C function which catches exceptions and can be used from Swift

/c @tgoyne @jpsim

### CODE REVIEW

**Comment by bdash** [comment]
There are other cases in `-[RLMProperty initSwiftPropertyWithName:indexed:property:instance:]` that look susceptible to this problem.

I wonder if instead of using `-valueForKey:` we could use an approach that accesses only the property we're after, avoiding the risk of calling KVC methods that happen to collide with the property?

**Comment by mrackwitz** [comment]
I wondered about the same question, but as we  use this on other places of the code as well to access the actual value, we would need to change them consequently, I guess. Otherwise it would just fail later.

Alternatively we would need further validations, which will at least increase the likelihood that if users override/intercept KVO accessors, that they still return correct value types. Instead we could also make them more strict and forbid implementations of those methods, which would help to avoid potential ambiguous code.

**Comment by mrackwitz** [comment]
## Summary of Discussions

As this verification is very specific, we should think of whether we could do that in a more general fashion at a different place. There are different options, which I want to layout here, so that we could decide on whether we settle on one of them or don't do any verification like that at all. It all boils down to enforcing our modified `RLMObject` class contract in differentiation to the expectations given from Foundation/Cocoa/`NSObject`. For all options, it could likely make sense to reduce the performance impact by executing them only in the Debug configuration and so not affecting distributed builds of the user's apps.

### Variant A: Check type on initial / every value access

Instead of relying on KVC directly via `valueForKey:`, we could instead encapsulating retrieving the properties value in a method / function. This could then contain further type verification and assert when the type conflicts with the expectations.

### Variant B: Scan & forbid overwritten alternate KVC accessors

As Realm implements custom accessors on `RLMObject` subclasses, we could just completely forbid users to implement alternate KVC methods. (e.g. `is<Key>`, `get<Key>`, …)

## Questions

/c @jpsim @tgoyne @bdash 

* Do these variants make sense and how I described them? How can they be improved?
* Is there any other variant I may have forgotten here?

**Comment by jpsim** [comment]
I'm not super clear on what kind of validation we should be doing, and how to achieve it. Thoughts @tgoyne @bdash?

**Comment by mrackwitz** [comment]
Closing as we all seem to hesitate to introduce further complexity in that direction, given that this isn't among our most critical objectives currently.

**Pull request closed without merging**
