### PR TITLE
Disable syncing to disk for everything but running on device

### PR DESCRIPTION
**Pull request by tgoyne**
Should save about three minutes of worker time on the CI PR runs.

### CODE REVIEW

**Comment by segiddins** [comment]
:+1:

**Comment by segiddins** [comment]
Needs a rebase and to also change Swift 2

**Comment by segiddins** [comment]
This should be good to go now, \c @jpsim

**Comment by tgoyne** [comment]
Only test failure was due to no devices plugged in to the CI machine.

**Comment by jpsim** [comment]
In practice, this change surprisingly seemed to be slowing down some performance tests on device. It'd be good to re-enable device tests on CI so we can look further into that.

**Pull request merged**
