### PR TITLE
Prevent a RLMRealm instance from escaping into another thread's autorelease pool

### LINKED ISSUE #4590: Realm file grows incredibly large on Realm 2.2.0+
Realm 2.2.0 seems to have introduced a bug somewhere that causes the realm file to grow exponentially under certain loads.

## Reproduction

```
#import "ViewController.h"
#import <Realm/RLMObject.h>
#import <Realm/RLMRealm.h>
#import <Realm/RLMRealmConfiguration.h>

@interface ViewController () {
    int runCount;
}

@end

@interface TestObject : RLMObject

@property int number;
@property NSString * data;

+ (TestObject *)randomTestObject;

@end

@interface TestThread : NSThread

@end

@implementation TestObject

+ (TestObject *)randomTestObject
{
    TestObject * result = [[TestObject alloc] init];
    result.number = arc4random_uniform(100);
    result.data = @"Hello world";
    return result;
}

+ (NSString *)primaryKey
{
    return @"number";
}

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.
}


- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

- (void)viewDidAppear:(BOOL)animated
{
    [super viewDidAppear:animated];
    runCount = 0;
    RLMRealmConfiguration * config = [RLMRealmConfiguration defaultConfiguration];
    [[NSFileManager defaultManager] removeItemAtPath:config.fileURL.path error:nil];
    [self runTest];
}

+ (void)insertionRun
{
    @autoreleasepool {
        RLMRealm * realm = [RLMRealm defaultRealm];
        [realm transactionWithBlock:^{
            for(int i = 0; i < 1000; i++) {
                [realm addOrUpdateObject:[TestObject randomTestObject]];
            }
        }];
    }

}

- (NSString *)realmFileSize
{
    NSURL * fileUrl = [RLMRealm defaultRealm].configuration.fileURL;
    double size = [[NSFileManager defaultManager] attributesOfItemAtPath:fileUrl.path error:nil].fileSize;
    NSString * unit = @"";
    if (size > 1024) {
        unit = @"KB";
        size /= 1024.;
    }
    if (size > 1024) {
        unit = @"MB";
        size /= 1024;
    }
    return [NSString stringWithFormat:@"%.1f%@", size, unit];
}

- (void)runTest
{
    if (runCount % 100 == 0) {
        NSLog(@"%d %@", runCount, [self realmFileSize]);
    }
    if (runCount++ >= 1000) {
        NSLog(@"File size at end: %@", [self realmFileSize]);
        return;
    }
    for (int i = 0; i < 10; i++) {
        [[[TestThread alloc] init] start];
    }
    [self.class insertionRun];
    dispatch_async(dispatch_get_main_queue(), ^{
        [self runTest];
    });
    
}


@end

@implementation TestThread

- (void)main
{
    [ViewController insertionRun];
}

@end

```

I'm just hitting the db from main thread as well as background threads very hard. I make sure that Realm objects on the background threads get autoreleased properly.

### Realm 2.1.2 test run

```
2017-01-26 13:43:06.188 RealmSizeTest[42489:13113867] Version 2.3.0 of Realm is now available: https://github.com/realm/realm-cocoa/blob/v2.3.0/CHANGELOG.md
2017-01-26 13:43:06.199 RealmSizeTest[42489:13113760] 0 4.0KB
2017-01-26 13:43:16.264 RealmSizeTest[42489:13113760] 100 960.0KB
2017-01-26 13:43:26.912 RealmSizeTest[42489:13113760] 200 1.2MB
2017-01-26 13:43:37.363 RealmSizeTest[42489:13113760] 300 1.2MB
2017-01-26 13:43:48.082 RealmSizeTest[42489:13113760] 400 1.2MB
2017-01-26 13:43:58.873 RealmSizeTest[42489:13113760] 500 1.2MB
2017-01-26 13:44:09.543 RealmSizeTest[42489:13113760] 600 1.2MB
2017-01-26 13:44:20.290 RealmSizeTest[42489:13113760] 700 1.2MB
2017-01-26 13:44:31.305 RealmSizeTest[42489:13113760] 800 1.2MB
2017-01-26 13:44:42.534 RealmSizeTest[42489:13113760] 900 1.2MB
2017-01-26 13:44:52.024 RealmSizeTest[42489:13113760] 1000 1.2MB
2017-01-26 13:44:52.025 RealmSizeTest[42489:13113760] File size at end: 1.2MB
```

### Realm 2.2.0 test run

```
2017-01-26 13:47:59.049 RealmSizeTest[43088:13132384] Version 2.3.0 of Realm is now available: https://github.com/realm/realm-cocoa/blob/v2.3.0/CHANGELOG.md
2017-01-26 13:47:59.072 RealmSizeTest[43088:13132277] 0 4.0KB
2017-01-26 13:48:09.774 RealmSizeTest[43088:13132277] 100 2.8MB
2017-01-26 13:48:23.945 RealmSizeTest[43088:13132277] 200 48.0MB
2017-01-26 13:48:39.185 RealmSizeTest[43088:13132277] 300 120.0MB
2017-01-26 13:48:54.536 RealmSizeTest[43088:13132277] 400 208.0MB
2017-01-26 13:49:11.571 RealmSizeTest[43088:13132277] 500 352.0MB
2017-01-26 13:49:29.719 RealmSizeTest[43088:13132277] 600 480.0MB
2017-01-26 13:49:48.606 RealmSizeTest[43088:13132277] 700 640.0MB
2017-01-26 13:50:09.208 RealmSizeTest[43088:13132277] 800 832.0MB
2017-01-26 13:50:30.976 RealmSizeTest[43088:13132277] 900 1152.0MB
2017-01-26 13:50:54.418 RealmSizeTest[43088:13132277] 1000 1280.0MB
2017-01-26 13:50:54.418 RealmSizeTest[43088:13132277] File size at end: 1280.0MB
```

## Conclusion

Clearly, something happened in 2.2.0 that causes this. A test on 2.3.0 produces identical results. Note that not *every* test run triggers this behaviour(some do reach a steady state around 4MB) but most runs do. We ran into this bug on our app in regular when we updated from Realm 1.1.0 to 2.2.0. One of our test devices ended up with a Realm file it couldn't open and on investigation we found it was over 700MB big and had triggered the mmap() limitation.

As a side note, the steady state reached on the 1.x line is usually around 200~300KB. In the 2.x line it's 1~4MB. So there was an increase there, but at least it still reaches a steady state. On 2.2.0 it just keeps growing endlessly

### PR DESCRIPTION
**Pull request by bdash**
This could result in growth of the Realm file's size as the `RLMRealm`'s lifetime may have been much longer than was expected.

Fixes #4590.

The diff if you exclude whitespace changes is:

```diff
diff --git a/Realm/RLMRealm.mm b/Realm/RLMRealm.mm
index 021a63a86..c9bdcc337 100644
--- a/Realm/RLMRealm.mm
+++ b/Realm/RLMRealm.mm
@@ -298,6 +298,7 @@ REALM_NOINLINE void RLMRealmTranslateException(NSError **error) {
         return nil;
     }
 
+    @autoreleasepool {
         // if we have a cached realm on another thread, copy without a transaction
         if (RLMRealm *cachedRealm = RLMGetAnyCachedRealmForPath(config.path)) {
             RLMRealmSetSchemaAndAlign(realm, cachedRealm.schema);
@@ -346,6 +347,7 @@ REALM_NOINLINE void RLMRealmTranslateException(NSError **error) {
                 [realm invalidate];
             }
         }
+    }
 
     if (config.cache) {
         RLMCacheRealm(config.path, realm);
```

### CODE REVIEW

**Comment by samacs** [comment]
I can confirm this also happens on versions 2.3.0 and 2.4.0.

**Comment by bdash** [comment]
Just to note: I omitted a change log entry because it's difficult to describe the scenarios that this fixes, and I don't want to overstate the impact of this change.

**Comment by bruce-lumo** [comment]
Will this fix databases that this has happened to when realm updates, or just prevent it in the future?

**Comment by bdash** [comment]
It only prevents the problem from occurring.

**Pull request merged**
