### PR TITLE
New browser icon

### LINKED ISSUE #1836: Realm Browser Icon Needs Updating
I was cruising through the Realm Browser's project file looking at what needs to be updated for our next release, and I noticed that its app icon still had the 'β' beta symbol on it. 

Unfortunately, upon removing the beta badge, all that was left behind a simple, flat, black 'R' on it's own. Needless to say, it looked pretty plain, and definitely didn't fit the app icon design standards of OS X Yosemite.

So, ideally, before we launch v1.0, it'd be great to have a nicer looking icon for the Realm Browser. :)

I just spent around 10 minutes playing with my copy of [Element 3D](https://www.videocopilot.net/products/element2/) and came up with this image:

realmbrowsericon

It's a OpenGL-rendered version of the Realm 'R' in the same 3D perspective as the Yosemite system apps. It's just to get the ball rolling for now, so what do you think? :)

/cc @yoshyosh

### PR DESCRIPTION
**Pull request by mrh-is**
Fixes #1836

### CODE REVIEW

**Comment by yoshyosh** [comment]
I think the previous icons were much nicer!

**Comment by timanglade** [comment]
lgtm. Can we fix the build? /cc @jpsim

**Comment by jpsim** [comment]
CI failure is unrelated. We're tracking a whole group of CI issues which will hopefully minimize these incidental failures [here](https://github.com/realm/realm-cocoa-private/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Aci).

**Comment by jpsim** [comment]
Thanks @mrh-is! Nice work.

**Pull request merged**
