### PR TITLE
[build.sh] Copy Realm.framework to OS X swift directory

### PR DESCRIPTION
**Pull request by segiddins**
\c @tgoyne

### CODE REVIEW

**Comment by tgoyne** [comment]
clean_retrieve is the oddly-named function for doing that.

**Comment by segiddins** [comment]
Should I use clean_retrieve, then?

**Comment by jpsim** [comment]
> Should I use clean_retrieve, then?

yes. and then :+1:

**Comment by segiddins** [comment]
Done -- it now uses `clean_retrieve`

**Pull request merged**
