### PR TITLE
Update to core 1.5.0

### PR DESCRIPTION
**Pull request by tgoyne**

### CODE REVIEW

**Comment by jpsim** [comment]
The CocoaPods CI job complained of not being able to find `handover.hpp`: https://ci.realm.io/job/objc_pr/3832/configuration=Release,swift_version=2.2,target=cocoapods/console

It's possible `handover.hpp` and `thread_confined.hpp` need to be added to the podspec.

Same thing goes for #3946 /cc @JadenGeller

**Comment by tgoyne** [comment]
The non-public headers thankfully don't need to be explicitly listed in the podspec anymore; the problem was just that it was relying on Xcode's extra-forgiving logic to let you include files anywhere in the project by just the bare name.

**Comment by jpsim** [comment]
Ah yes, that makes more sense. Thanks for clarifying.

**Comment by bdash** [comment]
👍

**Pull request merged**
