### PR TITLE
Fixing sequence iterators

### PR DESCRIPTION
**Pull request by austinzheng**
@jpsim 

Changes:
- Updated sequence, collection, and iterator protocols and types for Swift 3
- Restored use of NSFastEnumerationIterator
- Reenabled a test

### CODE REVIEW

**Comment by jpsim** [comment]
👍

**Comment by bdash** [comment]
Looks like the Realm/Swift directory may need separate versions for Swift 2.2 vs 3.0.

**Comment by jpsim** [comment]
@bdash you're absolutely right, though we haven't started porting `Realm/Tests/Swift` at all yet.

**Comment by bdash** [comment]
I'm referring to RLMSupport.swift, not the tests for using Realm Objective-C from Swift. I think it's a mistake to modify RLMSupport.swift it in place. It should be copied for Swift 3 like RealmSwift was (or #if'd, whichever).

**Comment by jpsim** [comment]
Ah yes, good point!

**Pull request merged**
