### PR TITLE
[Realm] Test that when cancelling inside a write block, the count of obj...

### PR DESCRIPTION
**Pull request by segiddins**
...ects doesn't change

\c @tgoyne @alazier

### CODE REVIEW

**Comment by alazier** [comment]
Could also hold onto `object` and make sure it is invalidated.

**Comment by segiddins** [comment]
You mean outside of the `write` block?

**Comment by jpsim** [comment]
> Could also hold onto object and make sure it is invalidated.

There's no point in doing that both inside and outside the block since it's the same transaction.

The ObjC rollback tests are much more comprehensive: https://github.com/realm/realm-cocoa/blob/master/Realm/Tests/RealmTests.mm#L778-L931

Since those tests only use the public API, we'd gain a lot more useful test coverage by porting those here rather than starting over in an ad-hoc fashion.

**Comment by segiddins** [comment]
> There's no point in doing that both inside and outside the block since it's the same transaction.

But that's an implementation detail :)

**Comment by tgoyne** [comment]
One of the reasons why the Swift tests are more manageable and understandable is because they're more limited in scope. Only the Swift-specific things should be tested, which in this case means verifying that the transaction was cancelled, but not that transaction canceling actually works correctly in general, since that's already covered by the obj-c tests.

**Comment by tgoyne** [comment]
:+1: to the current test.

**Pull request merged**
