### PR TITLE
fix Realm Objective-C's Swift 3 extensions

### PR DESCRIPTION
**Pull request by jpsim**
/cc @JadenGeller 

Closes https://github.com/realm/realm-cocoa/issues/3746.

### CODE REVIEW

**Comment by JadenGeller** [comment]
Maybe add a comment explaining that `RLMArray`'s `Sequence` conformance is implemented in the extension to `RLMCollection`.

**Comment by JadenGeller** [comment]
Glad we were able to fix these! 👍

**Comment by liuxuan30** [comment]
when it will be released?

**Comment by jpsim** [comment]
From twitter: https://twitter.com/realm/status/773665903946952704

> We'll be revising our Swift 3 API in the coming days and making an official release late next week!

**Comment by liuxuan30** [comment]
Thanks!

**Pull request merged**
