### PR TITLE
[Docs] Use the correct doc URL. Fixes #1890.

### LINKED ISSUE #1890: RealmSwift - Invalid Dash or Xcode docset feed
screen shot 2015-05-09 at 17 26 13

### PR DESCRIPTION
**Pull request by jpsim**
/cc @segiddins

### CODE REVIEW

**Comment by bdash** [comment]
:+1:

**Comment by segiddins** [comment]
Will this work, since the newest version will be under latest?

**Comment by jpsim** [comment]
> Will this work, since the newest version will be under latest?

Yes, because Jekyll copies `latest/{index.md,api}` to `$latest/{index.md,api}`.

**Comment by segiddins** [comment]
Ok, 👍🏻

**Pull request merged**
