### PR TITLE
[Draw, iOS] Specify custom credentials if logging in failed

### PR DESCRIPTION
**Pull request by stel**
No need to recompile the app anymore. The alert is show only if the logging in with the default credentials fails.

screen shot 2016-12-15 at 2 37 10 pm

@TimOliver, @bigfish24

### CODE REVIEW

**Comment by jpsim** [comment]
Going to let @TimOliver review this one.

**Comment by stel** [comment]
Unfortunately until we have log out and client reset we still need to reset the local data, so this functionality if only helpful until the first successful login.

**Comment by jpsim** [comment]
@TimOliver @stel @dhmspector  do we still need this given LoginKit and the current state of demos?

**Comment by TimOliver** [comment]
No, I don't think we need this anymore.

In fact, we have a repo for Draw in the Realm Demos repo now. We can probably remove this copy from Realm Cocoa now.

**Pull request closed without merging**
