### PR TITLE
Remove non-sync APIs marked `deprecated` and `unavailable`

### PR DESCRIPTION
**Pull request by austinzheng**
TODO:
- [x] Some of the deprecated Swift APIs removed in this commit should be brought back but marked `unavailable`

### CODE REVIEW

**Comment by austinzheng** [comment]
CI ran the wrong branch. I'll re-run it before I merge.

**Comment by austinzheng** [comment]
I don't know why the tvOS tests are failing. A bunch of the CI machines seem to be disconnected, hence more test failures. Finally, the object server tests are failing on the same mysterious child process issue Mark saw on Friday.

**Comment by austinzheng** [comment]
All jobs that have failed failed because of CI issues. The last outstanding job looks like it's stuck on CI issues as well. I'm going to merge.

**Comment by bdash** [comment]
Change log entry?…

**Comment by austinzheng** [comment]
Oops. I'll push one to the branch.

**Pull request merged**
