### PR TITLE
Add iOS 7 simulator tests

### PR DESCRIPTION
**Pull request by kishikawakatsumi**
- [x] Investigate the test cases that rarely fails

```
SwiftUnicodeTests
    ✓ testUTF8PropertyWithUTF8StringContents (0.075 seconds)
    ✓ testUTF8PropertyWithUTF8StringContents_objc (0.101 seconds)
    ✓ testUTF8StringContents (0.158 seconds)
    ✓ testUTF8StringContents_objc (0.146 seconds)

ArrayPropertyTests
  testAddInvalidated, failed: caught "RLMException", "open() failed: No such file or directory"
  <unknown>:0\

  testArrayDescription, failed: caught "RLMException", "open() failed: No such file or directory"
  <unknown>:0\

  testCrossThreadAccess, failed: caught "RLMException", "open() failed: No such file or directory"
  <unknown>:0\

  testDeleteLinksAndObjectsInArray, failed: caught "RLMException", "open() failed: No such file or directory"
  <unknown>:0\

  testDeleteObjectInArrayProperty, failed: caught "RLMException", "open() failed: No such file or directory"
  <unknown>:0\

...
```

It was reproduced a few times locally, but it has not occurred now.

### CODE REVIEW

**Comment by jpsim** [comment]
@kishikawakatsumi let me know when this is no longer WIP and we'll make CI run `test-ios7-static`, run the job a few times to make sure it's stable, and then merge it in.

**Comment by kishikawakatsumi** [comment]
> run the job a few times to make sure it's stable, and then merge it in.

I think so. @jpsim 
If frequently reproduced after try several times, I'll investigate. Otherwise merge this for now.

**Comment by kishikawakatsumi** [comment]
retest this please

**Comment by kishikawakatsumi** [comment]
retest this please

**Comment by jpsim** [comment]
@kishikawakatsumi please be aware that at the moment, the objc_pr job on Jenkins doesn't run `test-ios7-static`. I'll enable that for you in a minute.

**Comment by segiddins** [comment]
Should I add a matrix entry for the ios7-static?

**Comment by jpsim** [comment]
@kishikawakatsumi please add a `verify-ios7-static` command to `build.sh` (all the cocoa PR CI jobs start with `verify-`) and we'll enable that matrix item for just this branch so we can confirm it's working before rolling it out to all PRs.

**Comment by kishikawakatsumi** [comment]
@jpsim Added `verify-ios7-static` and `verify-ios7-static-debug` https://github.com/realm/realm-cocoa/commit/28a2cd5b1556c035dae9e379e5388963f9715437.
It executes `test-ios7-static` each configuration. It is unnecessary to execute `examples-ios` I think.

**Comment by jpsim** [comment]
Agreed, it's unnecessary to execute `examples-ios` since that's already being tested.

**Comment by jpsim** [comment]
I just ran CI with `ios7-static` and `ios7-static-debug` 5-6 times and all those tests passed, so this seems pretty reliable now. Merging.

**Comment by jpsim** [comment]
Thanks @kishikawakatsumi!

**Pull request merged**
