### PR TITLE
Install an uncaught exception handler to close write transactions whe…

### PR DESCRIPTION
**Pull request by segiddins**
…n possible

Might help out in a few situations where https://github.com/realm/realm-cocoa/issues/2159 is an issue.

\c @tgoyne @bdash

### CODE REVIEW

**Comment by jpsim** [comment]
I can't tell why you'd only want to cancel the write transactions for the thread the exception was thrown from rather than from all cached realms...

Overall, this PR makes me very uneasy and feels like much more of a hack than addressing the root cause (which may be unfeasible to address given the state of mutexes on Apple platforms).

**Comment by tgoyne** [comment]
We'd prefer to cancel all of them, but trying to cancel the ones for other threads has a good chance of causing another crash that hides the original problem.

**Comment by jpsim** [comment]
It also worries me that this is hard to test, but I don't think there's much overhead in installing this handler, and the process is already (hopefully) like to be terminated by the point this is hit, so I think this is safe to do. :+1: 

You could add a changelog "bugfix" entry along the lines of:

> Processes crashing due to an uncaught exception during a write transaction will longer cause other processes using the same Realm to hang indefinitely.

**Comment by segiddins** [comment]
CHANGELOG added

**Comment by jpsim** [comment]
:+1:

**Comment by segiddins** [comment]
retest this please

**Comment by tgoyne** [comment]
:+1:

**Pull request merged**
