### PR TITLE
[RLMProperty] Disallow creating a property of type RLMObject

### LINKED ISSUE #1465: Creating an object property of type RLMObject should throw
A users was trying to do this in swift which should throw. This should also throw if done from objc.

### PR DESCRIPTION
**Pull request by segiddins**
Closes #1465.

\c @alazier

### CODE REVIEW

**Comment by tgoyne** [comment]
:+1:

**Comment by tgoyne** [comment]
changelog

**Comment by alazier** [comment]
I think you should instead be changing RLMISSubClass rather than rewriting each instance. Should maybe be renamed to RLMIsObjectClass or something, and we should fix other cases where we have made this change. We should not be duplicating this logic/test throughout the code base.

**Comment by segiddins** [comment]
@alazier done

**Comment by alazier** [comment]
What about the other places `RLMIsSubClass` is called? Should those cases also instead be `RLMIsObjectClass`? If so we can remove `RLMIsSubClass` altogether in favor of the new method.

**Comment by segiddins** [comment]
I replaced all the relevant places, but the new function uses `RLMIsSubclass` under the hood.

**Comment by segiddins** [comment]
(The test failure is `testBeginWriteTransactionsRefreshesRealm`, which has been failing intermittently for a while)

**Comment by segiddins** [comment]
@alazier think I'm good to merge this?

**Pull request merged**
