### PR TITLE
Enable running Swift sources of Realm Objective-C tests in Swift 4

### PR DESCRIPTION
**Pull request by jpsim**
by applying a workaround to [rdar://33514802](http://www.openradar.me/33514802) as suggested here: https://twitter.com/aikoniv/status/889961905464397824

### CODE REVIEW

**Comment by jpsim** [comment]
I had to change this a bit to fix support for Xcode 8.x and fallout from #5148. @austinzheng do you mind confirming that this is alright by you?

**Comment by austinzheng** [comment]
The changes look fine to me. I assume adding `mutating` won't break the Xcode 8 builds.

**Comment by austinzheng** [comment]
It looks like these changes might still be problematic? Many of the CI jobs are failing because of compilation failures.

**Comment by jpsim** [comment]
> It looks like these changes might still be problematic? Many of the CI jobs are failing because of compilation failures.

Digging through the CI logs, none of it made sense based on the contents of this PR, leading me to think that we were hit by realm/ci#109 again.

I reran the jobs and everything looks good now.

**Pull request merged**
