### PR TITLE
Fix unsafe uses of __unsafe_unretained

### PR DESCRIPTION
**Pull request by tgoyne**
Fix a place where a newly created object was being assigned to a __uu pointer, and make all __uu pointers const to ensure that the same thing isn't being done elsewhere.

@alazier

### CODE REVIEW

**Comment by segiddins** [comment]
Is there a compiler warning we can enable to help us prevent this happening in the future?

**Comment by tgoyne** [comment]
Not that I know of, but only ever using const __uu pointers will make it impossible for this exact issue to occur (there are plenty of other ways to run into problems with non-owning pointers).

**Comment by danielpovlsen** [comment]
Did you find other places where new objects were assigned to a __uu pointer?

**Comment by tgoyne** [comment]
No.

**Comment by danielpovlsen** [comment]
If __uu is *much* faster than the default (__strong), wouldn't it make sense to work around the issue for `RLMAddLinkedObject()`? How critical is this function?

**Comment by danielpovlsen** [comment]
I mean, we get back this object, just to figure out the row index, right?

**Comment by tgoyne** [comment]
```
- (void)testAssignLink {
    RLMRealm *realm = RLMRealm.defaultRealm;

    [realm beginWriteTransaction];
    CircleObject *circle = [CircleObject createInRealm:realm withObject:@[@"", NSNull.null]];
    [realm commitWriteTransaction];

    [self measureBlock:^{
        [realm beginWriteTransaction];
        for (int i = 0; i < 50000; ++i) {
            circle.next = circle;
        }
        [realm cancelWriteTransaction];
    }];
}
```

This hits the worst-case for this change and is slowed down from 525ms to 563ms on my 4S.

**Comment by alazier** [comment]
We can add the optimization back in. This code is changed anyways on the swift branch - I can re-make these changes on this branch.

**Comment by alazier** [comment]
Looks good to me :+1:

**Pull request merged**
