### PR TITLE
Reduce target duplication in RealmSwift's Xcode project

### PR DESCRIPTION
**Pull request by bdash**
The framework targets for iOS and OS X are folded into a single target since they're virtually identical. The test targets for iOS, iOS devices, and OS X are folded into a single target with a small amount of conditional logic to preserve the small behavioral differences between the targets.

/cc @jpsim @segiddins @tgoyne

### CODE REVIEW

**Comment by segiddins** [comment]
This will be a nightmare to reconcile with https://github.com/realm/realm-cocoa/pull/1942, which I'm actively working on as we speak

**Comment by bdash** [comment]
@segiddins I'll handle resolving the conflicts that arise once that's merged in.

**Comment by bdash** [comment]
Rebased on top of #1942.

**Comment by segiddins** [comment]
failure seems unrelated

**Comment by jpsim** [comment]
Nice work :+1:

**Pull request merged**
