### PR TITLE
Add more files to private_header_files

### LINKED ISSUE #1388: RLMAccessor.h:20:9: 'RLMObjectStore.hpp' file not found - podspec issue
Related issue: https://github.com/realm/realm-cocoa/issues/1280
Related PR: https://github.com/realm/realm-cocoa/pull/1358

I am now getting this error when installing Realm 0.90.0 via cocoapods 0.36.0.beta.1

```
RLMAccessor.h:20:9: 'RLMObjectStore.hpp' file not found
```

image

### Podfile:

```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!

pod 'Realm', '0.90.0'
```

### PR DESCRIPTION
**Pull request by tgoyne**
Closes #1388.

### CODE REVIEW

**Comment by jpsim** [comment]
:+1:

**Comment by jpsim** [comment]
or just set the public header files explicitly.

**Comment by ldiqual** [comment]
Did anyone actually try the new podspec? I'm a bit concerned since the last two versions had a broken podspec. I'll try this one tonight.

**Comment by segiddins** [comment]
I think we should just explicitly specify the public headers.

**Comment by jpsim** [comment]
@ldiqual we usually test the podspec manually, but we're in the process of adding a check to our continuous integration server to confirm the Realm pod works at all times (#1395).

**Pull request merged**
