### PR TITLE
Improve type-safety of RLMResults subscript by making return type generic rather than `id`

### PR DESCRIPTION
**Pull request by JadenGeller**

### CODE REVIEW

**Comment by JadenGeller** [comment]
@austinzheng

**Comment by austinzheng** [comment]
👍

**Comment by tgoyne** [comment]
Also need to update the swift 2.2 version of the tests as they now warn about pointless casts.

**Comment by JadenGeller** [comment]
I thought Swift 2.2 didn't import Objective-C generics? I'll check it out and find out.

**Comment by JadenGeller** [comment]
@tgoyne You're right, there *are* warning! But, not because the generics were imported into Swift 2.2. Changing the return type to the generic type imported it as `RLMObject`, the class constraint on the generic. 👍

**Comment by bdash** [comment]
This should really have had an entry in the changelog

**Comment by JadenGeller** [comment]
@bdash Sorry, should I create a new PR to add an entry? I'm not entirely clear on what sort of changes require an entry. Is it anything that breaks the API (warnings or errors), introduces features, or fixes major bugs?

**Comment by bdash** [comment]
Any changes in API, new features, enhancements to existing features, or bug fixes should have changelog entries. The only things that typically don't get changelog entries are internal refactoring with no user-visible consequences. I'd also exclude Swift 3 specific changes for now since we don't officially support it, and we'll likely be announcing all of the changes in a single location when our support for it becomes official.

It'd be worth adding an entry still as we've not yet released this change.

**Pull request merged**
