### PR TITLE
Run the strip frameworks script for the swift examples

### PR DESCRIPTION
**Pull request by segiddins**
Might help https://github.com/realm/realm-cocoa/issues/1864.

\c @jpsim @mrackwitz

### CODE REVIEW

**Comment by segiddins** [comment]
Perf test failure is surely unrelated

**Comment by jpsim** [comment]
Well we should probably be drinking our own kool-aid, so :+1:

**Comment by mrackwitz** [comment]
:+1:

**Comment by danielpovlsen** [comment]
:+1: for hand optimising the project :-)

**Pull request merged**
