### PR TITLE
[Browser] Use modular imports

### PR DESCRIPTION
**Pull request by segiddins**
Also now uses the Realm.Private module instead of including a custom Realm_Private.h

\c @jpsim @GreatApe

### CODE REVIEW

**Comment by segiddins** [comment]
@alazier addressed your comments

**Comment by alazier** [comment]
rebase

**Comment by segiddins** [comment]
@alazier rebased

**Comment by alazier** [comment]
:+1:

**Comment by GreatApe** [comment]
Sorry I missed this until now, but always nice with some spring cleaning of headers!

**Pull request merged**
