### PR TITLE
add favicon to html docs. fixes #2220

### LINKED ISSUE #2220: Favicon for api docs

### PR DESCRIPTION
**Pull request by jpsim**
Fixes #2220 /cc @yoshyosh

### CODE REVIEW

**Comment by jpsim** [comment]
I opted to link to the favicons on realm.io so we wouldn't have to maintain a separate set here. @yoshyosh are these URLs stable?

**Comment by yoshyosh** [comment]
I believe they should be, can you confirm @mrh-is ?

**Comment by mrh-is** [comment]
They've been that way for a while, and we can make them stable going forward. If you like them somewhere else, I can move them very easily.

tl;dr: Yes, they are stable.

**Comment by jpsim** [comment]
Cool! Thanks.

**Pull request merged**
