### PR TITLE
Release 0.98.7

### PR DESCRIPTION
**Pull request by jpsim**
Did this one by reverting breaking changes rather than cherry picking the changes we want over 0.98.6, since that seems safest given the number of changes we do want from `master`. /cc @bdash @tgoyne

### CODE REVIEW

**Comment by tgoyne** [comment]
The diff from 0.98.6 looks reasonable to me.

**Comment by jpsim** [comment]
CocoaPods job failure is due to a `v0.98.7` tag not existing yet.

```
[!] Error installing Realm
 -> Realm (0.98.7)
    - WARN  | url: The URL (https://realm.io/docs/objc/0.98.7) is not reachable.
    - ERROR | [iOS] unknown: Encountered an unknown error ([!] /usr/local/bin/git clone https://github.com/realm/realm-cocoa.git /var/folders/np/5y4sgt8x3r13sk7x0n31z_3m0000gn/T/d20160413-13633-1gu378n --single-branch --depth 1 --branch v0.98.7

Cloning into '/var/folders/np/5y4sgt8x3r13sk7x0n31z_3m0000gn/T/d20160413-13633-1gu378n'...
warning: Could not find remote branch v0.98.7 to clone.
fatal: Remote branch v0.98.7 not found in upstream origin
) during validation.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error and 1 warning.
```

Disabling the podspec lint step makes the `verify-cocoapods` job pass for me locally.

**Comment by bdash** [comment]
Do the changes related to designated initializers break source compatibility with v0.98.6?

**Comment by jpsim** [comment]
No, see the discussion in https://github.com/realm/realm-cocoa/pull/3305#issuecomment-199411883

**Comment by bdash** [comment]
👍

**Comment by jpsim** [comment]
0.98.7 released: https://github.com/realm/realm-cocoa/releases/tag/v0.98.7

**Pull request closed without merging**
