### PR TITLE
Make Realm collections conform to CollectionType

### PR DESCRIPTION
**Pull request by segiddins**
\c @jpsim @alazier

### CODE REVIEW

**Comment by segiddins** [comment]
We could also make `List` conform to `RangeReplaceableCollectionType`, if we want to.

**Comment by jpsim** [comment]
Unless there are technical limitations from doing so, it'd be nice to have a `RealmCollectionType` protocol conforming to `CollectionType` and add other realm niceties.

**Comment by segiddins** [comment]
Rebased

**Comment by jpsim** [comment]
Nice! :+1: :+1:

**Comment by alazier** [comment]
I think the ordering of methods in Results is kind of confusing - a bunch of protocol implementation interspersed with other methods. Since we also don't have explicit tests for this might be nice to have these methods in an extension or at the end of the class.

**Comment by segiddins** [comment]
@alazier done

**Comment by alazier** [comment]
That seems a lot more sensible. :+1:

**Pull request merged**
