### PR TITLE
Removed Realm Browser project and build phases

### PR DESCRIPTION
**Pull request by TimOliver**
/cc @jpsim @tgoyne @segiddins  @timanglade 

I've removed the entire Realm Browser project directory from this repo, and removed all references to the browser in the build script. Please let me know if that's all good, or if I've missed anything. Thanks!

### CODE REVIEW

**Comment by jpsim** [comment]
:+1: I'll update Jenkins to not package the browser

**Comment by jpsim** [comment]
The CI failure was because #2097 hasn't been merged yet.

**Comment by segiddins** [comment]
:+1: seems fine!

**Comment by TimOliver** [comment]
Excellent! Thanks for that!

The Realm Browser is now awaiting review in iTunes Connect. If/when it gets approved and released, I'll go ahead and merge this PR.

Thanks!

**Comment by jpsim** [comment]
@TimOliver you don't have to wait for App Store availability to merge this, since the location of the browser's source isn't affected by where the binary is available.

**Comment by timanglade** [comment]
Can you leave a tools/README.md that just has a quick sentence in there pointing people to the new repo? Will be useful to have that for a bit, so people don’t think we took the browser closed-source. And then in a couple of months we can remove the tools/ directory altogether.

**Pull request merged**
