### PR TITLE
Synchronize access to the accessor linked list with a spinlock

### PR DESCRIPTION
**Pull request by segiddins**
Another take at #1684.

\c @tgoyne @alazier

### CODE REVIEW

**Comment by tgoyne** [comment]
Needs to be something like `void RLMSetRow(RLMObjectBase *object, RLMObjectSchema *objectSchema, NSUInteger index)` with the assignment to `_row` within the lock. Copying or assigning a `Row` object also causes the accessor linked-list to be modified.

**Comment by tgoyne** [comment]
There's at least one more place where `_row` is assigned to (in RLMArrayLinkView fast enumeration).

There's also more operations that need to be locked. `move_last_over` also mutates the linked list (and it being able to update row accessors is the entire point of the list), as does `advance_read` when applying a transaction which removed rows. The latter case needs to lock all of the object schemas which have active table references.

**Comment by astigsen** [comment]
Why are the locks needed? Are there cases where the schema is being used by
multiple threads?​

**Comment by tgoyne** [comment]
It's to handle the scenario where the user captures a reference to an object that's never used on the wrong thread, but is released and deallocated on the wrong thread.

**Pull request closed without merging**
