### PR TITLE
Add a test for using an RLMObject subclass created at runtime

### PR DESCRIPTION
**Pull request by segiddins**
For no particular reason...

### CODE REVIEW

**Comment by tgoyne** [comment]
ios-device job died while running the new test.

**Comment by segiddins** [comment]
Ran this a few times on the mini and it passed each time.

**Comment by segiddins** [comment]
retest this please

**Comment by segiddins** [comment]
Device tests now pass, only failure was `InterprocessTest.testNotificationsForChangesWhileSuspended`

**Comment by bdash** [comment]
:+1:

**Comment by jpsim** [comment]
why not? :+1:

**Pull request merged**
