### PR TITLE
Fix issue where sync does not properly reconnect

### PR DESCRIPTION
**Pull request by austinzheng**
Requires https://github.com/realm/realm-object-store/pull/451
Fixes: #4905 
~Pending testing~

Changes:
- Update sync dependency to 1.10.0
- Use object equality comparison to check the error domain
- Update object store to pull in related fixes at that layer
- Also, remove a spurious print statement

### CODE REVIEW

**Comment by austinzheng** [comment]
Looks like a bunch of CI machines are indisposed.

**Comment by jpsim** [comment]
> Disabled permission offer/response tests broken by the core/sync upgrade (unrelated to this change)

Actually, it's the added call to `SyncManager::shared().cancel_reconnect_delay();` in `RLMSyncSessionRefreshHandle.mm` that's causing the permission tests to fail. Removing it makes all object server tests pass.

**Comment by austinzheng** [comment]
There's no conceivable good reason why the added call should be triggering the assert that causes the tests to fail. Anyways I won't be able to look at this any further until I get back.

**Comment by austinzheng** [comment]
Sorry, that last comment was a bit snippy. When I get access to my work machine again I'll investigate the problem further and see if it's something related to the models, object store, or if I can file a bug against sync with useful reproduction data.

**Comment by austinzheng** [comment]
Worked around the issue (and improved the fix overall) through the most recent commit + https://github.com/realm/realm-object-store/pull/454.

**Comment by austinzheng** [comment]
The reason all the tests are failing is because there's an object store-binding dependencies mismatch, and there are some code changes required to get both in sync.

**Comment by kishikawakatsumi** [comment]
@austinzheng Should `REALM_SYNC_VERSION` on `realm-cocoa`'s `dependencies.list` to `1.9.0` as well as `object-store`'s one?

**Pull request merged**
