### PR TITLE
Add support for SwiftPM based dependency managers

### PR DESCRIPTION
**Pull request by Jeehut**
This adds support for SwiftPM manifest based dependency managers. Specifically this adds support for installing via [Accio](https://github.com/JamitLabs/Accio) but will probably also work with SwiftPM once it's integrated into Xcode.

Please note that this project is part of Accio's official [integration tests](https://github.com/JamitLabs/Accio/tree/work/1000-frameworks/Demo/Shared/AppDependencies) within the [Demo project](https://github.com/JamitLabs/Accio/tree/work/1000-frameworks/Demo).

Also, as there is no documentation file in the repo, here's the description on how to install Accio for copy & paste purposes into the official documentation on realm.io:

--- 

## Installation via Accio

Add the following to your `Package.swift`:

```swift
.package(url: "https://github.com/realm/realm-cocoa.git", .upToNextMajor(from: "3.15.0")),
```

Next, if your project uses Swift code, add `RealmSwift` to your App targets dependencies like so:

```swift
.target(
    name: "App",
    dependencies: [
        "RealmSwift",
    ]
),
```

Specifying `RealmSwift` will automatically integrate `Realm` for Objective-C usage, too. If you only need the Objective-C variant of Realm, specify `Realm` in your targets dependencies instead.

Then run `accio update`.

### CODE REVIEW

**Comment by Dschee** [comment]
Any updates on this?

**Comment by Dschee** [comment]
@tgoyne Is there anything holding this off from being merged? This PR is waiting 6 weeks now without any feedback whatsoever ... would be great if support for installation via Accio was added!

**Comment by tgoyne** [comment]
I started trying to set up the CI stuff to test that this continues to work, but then got sidetracked. I guess there's no real need to wait on that with how simple the project manifest is, and since we're testing Carthage installation that should cover ensuring that it continues to build properly.

I think we now need a [MongoDB contributor agreement](https://www.mongodb.com/legal/contributor-agreement) to merge things.

**Comment by Dschee** [comment]
@tgoyne Ah, no sorry. I won't do some extra licensing work just for you guys to merge this. Please continue to demand such a weird and unnecessary thing to make contirbuting a hassle. This will really improve the code base!

**Comment by bmunkholm** [comment]
Hi @Dschee - sorry you feel that way. It's not our intention to make contributing a hassle - on the contrary, and we highly appreciate your effort. It may be considered unnecessary (for us non-lawyers) but it's at least not weird as it is standard practice if you are contributing to any OSS maintained by companies. It basically just ensures both parties are legally agreeing. In any case, thanks for the effort and we will work on this feature later.

**Comment by Dschee** [comment]
I can see that, but isn't this open source software and things are clarified through the License the code is under? Also, if the agreement process was just a few clicks, I'd have done that and not complained. But it isn't. The link you posted doesn't even contain a process or explain anything – I'd have to figure out on my own how I could agree ... it's just not an easy process. Maybe you should consider streamlining that process before making that a requirement. Or live with how it is now.

**Comment by bmunkholm** [comment]
@Dschee It sure is open source. But still, you have to actively "hand over the rights to the code you make" to the project. [This](https://www.clahub.com/pages/why_cla) explains it very short.   
I haven't actually gone through the new MongoDB SLA process (the acquisition is rather new). If it makes a difference or is simpler you can also use the [Realm CLA](https://docs.google.com/forms/d/e/1FAIpQLSdEDqd2jolmzX9uUHmvdqgrhopueTOwJXMw300Wbjj3tJcD9w/viewform?fbzx=4154977190905366979) which is based on Apache CLA. It is just filling in your contact details and click submit). We surely want it to be easy, so I do appreciate your feedback if you think we can make it easier in any way.
Appreciate your understanding.

**Comment by Dschee** [comment]
Yes, that one was straightforward and I have just filled the form. So, reopening then.

**Comment by juliengdt** [comment]
Ahoy, any updates on that ? Seems quite obvious to have spm service-based supported such as Accio. This is quite annoying to have all my app managed by Accio ... and realm by Carthage ... 

👎

**Comment by tgoyne** [comment]
We now have a Package.swift for building with swiftpm. If that doesn't work with Accio then supporting both that and Accio seems to be mutually exclusive?

**Comment by Jeehut** [comment]
@tgoyne It's actually the other way around: When a library supports Carthage & Accio, it should automatically have Accio support as well. @juliengdt Did you try installing the latest Realm versions with Accio? Why didn't it work? Feel free to open an issue on Accio as Realm is now supporting SwiftPM. @tgoyne I couldn't find documentation about Realms SwiftPM support though. Do you have a pointer where I can find it?

**Comment by Browserside** [comment]
Can't believe this is taking so much time. SPM support is need of the hour!

**Comment by leemaguire** [comment]
@Browserside We have full SPM support

**Pull request closed without merging**
