### PR TITLE
Upgrade to core 6.0.23

### PR DESCRIPTION
**Pull request by tgoyne**

### CODE REVIEW

**Comment by gongzhang** [comment]
@tgoyne `coreVersionStr` in `Swift.package` also needs to be updated in this PR, right? 😊

**Comment by aalenliang** [comment]
When will this PR be merged?

**Comment by tgoyne** [comment]
When it is passing the tests.

**Comment by marciogranzotto** [comment]
Was this supposed to fix https://github.com/realm/realm-cocoa/issues/6671? Pulling the latest commit still gives me the same error. Also if I don't use my Realm DB in the app, I don't have the issue.

I'm running with cocopods like so:
```ruby
pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :commit => 'ee357b28e6fec9fc25fa65a5e2afff063825a69c', :submodules => true
```

**Comment by tgoyne** [comment]
This branch currently doesn't build at all when installing via cocoapods.

**Comment by marciogranzotto** [comment]
Hm... cocoapods didn't throw any errors, but it's possible that it only falls back to the release version or something...
```bash
$ pod install --clean-install                                                                                                  [16:29:32]
Analyzing dependencies
Pre-downloading: `RealmSwift` from `https://github.com/realm/realm-cocoa.git`, commit `ee357b28e6fec9fc25fa65a5e2afff063825a69c`, submodules `true`
Downloading dependencies
Installing RealmSwift 5.3.5
Generating Pods project
Integrating client project
Pod installation complete! There are 21 dependencies from the Podfile and 56 total pods installed.
```

**Comment by thodang888** [comment]
I tested my app on iOS 12 with release v5.3.6 and my app freezes. This issue doesn't occur if I don't use v5.3.6. Do anyone have the same problem with me?

**Comment by SquaredTiki** [comment]
We've been seeing this too, raised #6749.

**Comment by thodang888** [comment]
> We've been seeing this too, raised #6749.

With my situation, I reverted the Realm database to the last version that I used and recommended users should use iOS 14 beta 7.

**Pull request merged**
