### PR TITLE
fix inverted old/new versions

### LINKED ISSUE #3113: Incorrect message: Provided schema version 4 is less than last set version 3.
The message 

```cpp
m_what = "Provided schema version " + std::to_string(old_version) + " is less than last set version " + std::to_string(new_version) + ".";
```

is not always correct, because it can happen, e.g. when switching branches, that the Realm migration version is already higher than the last in code, where the message displays as follows:

```
Provided schema version 4 is less than last set version 3.
```

My CPP skill are absent so I didn't try to fix it myself, but I guess a simple comparison should be enough:

```
joiner = old_version > new_version ? "greater" : "less"
```

https://github.com/realm/realm-cocoa/blob/facde33440f2d46ece3e32ca60ff58f2a9028080/Realm/ObjectStore/object_store.cpp#L504

### PR DESCRIPTION
**Pull request by jpsim**
in InvalidSchemaVersionException. Fixes #3113. /cc @tgoyne

### CODE REVIEW

**Comment by bdash** [comment]
Can we test this?

**Comment by jpsim** [comment]
test adapted to match expected exception message

**Comment by bdash** [comment]
:+1:

**Comment by mrackwitz** [comment]
Shouldn't this get a changelog entry?

**Comment by jpsim** [comment]
A changelog entry doesn't seem necessary here.

**Pull request merged**
