### PR TITLE
Fixes for Swift 3 DP 1

### PR DESCRIPTION
**Pull request by austinzheng**
@bdash @tgoyne @jpsim 

Changes:
- Fixed imported enum cases
- Annotated some APIs with @discardableResult
- Added "_ =" to tests that intentionally ignore return values to quiet warnings

NOTE: JP pointed out a few tests that are still commented out. A subsequent commit will restore them.

### CODE REVIEW

**Comment by tgoyne** [comment]
I sorta think `create()` should be discardable since calling it purely for the side effect is perfectly reasonable.

`migrateRealm()` shouldn't be (actually, it should be throwing an exception...).

**Comment by austinzheng** [comment]
Agreed. It makes sense to just want to persist an object to a Realm directly without further manipulating it.

**Comment by austinzheng** [comment]
I force pushed over the previous commit since there's not much point in comparing the differences. I made a few functional changes.

**Comment by tgoyne** [comment]
👍

**Pull request merged**
