### PR TITLE
Update Sync.swift docs with deprecation warning.

### PR DESCRIPTION
**Pull request by bmunkholm**

### CODE REVIEW

**Comment by tgoyne** [comment]
`- warning` is correct, and changing it to `@warning` will make the docs not render correct inside Xcode.

**Comment by bmunkholm** [comment]
Ah ok , so that works differently for objc which uses @?

**Comment by tgoyne** [comment]
Yes, objc and swift have different doc comment syntaxes.

**Comment by bmunkholm** [comment]
Haha and I guessed I found the issue with the rendering.

Ok then we could just remove the year old note about it being experimental.

**Comment by bmunkholm** [comment]
@tgoyne I fixed the wrong warning syntax. Is this good now?

**Pull request merged**
