### PR TITLE
Honor the schema version set in the configuration in `+[RLMRealm migrateRealm:]`

### PR DESCRIPTION
**Pull request by tgoyne**

### CODE REVIEW

**Comment by bdash** [comment]
:+1:

**Comment by jpsim** [comment]
This seems to have broken all the Swift migration tests.

**Comment by bdash** [comment]
The deprecated `migrateRealm(path:encryptionKey:)` isn't setting a schema version on its configuration. All of the tests are using this legacy API rather than the new `migrateRealm(configuration:)`.

**Comment by tgoyne** [comment]
Now passes all tests with a few more functional changes.

**Comment by jpsim** [comment]
:+1:

**Pull request merged**
