### PR TITLE
Improve `RLMRealm` Swift interface for initialization and transactions

### PR DESCRIPTION
**Pull request by JadenGeller**
Annotates `RLMRealm` members for better import into Swift as part of https://github.com/realm/realm-cocoa/issues/3790. Note that this is a source-breaking change for Swift users of Realm Objective-C. If we care to not break source compatibility for that particular user base, then we should delay merging this until a large version bump.

### CODE REVIEW

**Comment by JadenGeller** [comment]
@austinzheng

**Comment by austinzheng** [comment]
Looks good to me! I don't know what our source-breaking story is for Swift users of Realm Objective-C, so please ask Thomas, Mark, or JP.

**Comment by JadenGeller** [comment]
^^ @tgoyne @bdash @jpsim

**Comment by tgoyne** [comment]
A breaking change like this would mean bumping the version to 2.0, and a month after we released 1.0 is far too early for that. The Swift 2.2 -> 3 transition is somewhat of a special case in that it's effectively a new language that we're targeting so there is no older versions to maintain compatibility with, but I'm assuming that anything based on annotating the obj-c API can't be swift 3-only.

**Comment by JadenGeller** [comment]
To the best of my understanding, yes. Unless…
Is there a way the preprocessor can detect what version of Swift the user is compiling with?

**Comment by JadenGeller** [comment]
Looks like such a macro might be coming soon! https://twitter.com/UINT_MIN/status/751164808553046016

**Comment by JadenGeller** [comment]
Assigning to myself to remind me to update this once such a feature becomes available.

**Comment by JadenGeller** [comment]
Actually, I'll close this PR for now, and make a new PR when such a feature is available. Until then, these sorts of changes can live on this branch: https://github.com/realm/realm-cocoa/tree/jg-improved-swift-import

**Pull request closed without merging**
