### PR TITLE
Add underscore to camel case mapping when initializing

### PR DESCRIPTION
**Pull request by kylebshr**
Created for issue #2615 — please discuss if this is appropriate to add! I find it very useful.

### CODE REVIEW

**Comment by kylebshr** [comment]
I'm not too sure where and how to add tests in the grand scheme of this project — would love some pointers on that.

**Comment by kylebshr** [comment]
Closing due to decision reached in #694

**Comment by jpsim** [comment]
Thanks for understanding, @kylebshr!

**Comment by kylebshr** [comment]
Of course — thanks for pointing out the proper way to do what I wanted!

**Pull request closed without merging**
