### PR TITLE
Remove ** from header paths

### PR DESCRIPTION
**Pull request by cltnschlosser**
Fixes https://github.com/realm/realm-cocoa/issues/7113 in my project. Realm has a bit of a complicated setup, but I think it should work for all cocoapods use cases.

Resolves https://github.com/realm/realm-cocoa/issues/7113

### CODE REVIEW

**Comment by cltnschlosser** [comment]
Hmm, it looks like the way the CI is set up, the tests won't work if the branch is in a fork. @dianaafanador3 Could you or someone else open a PR with my changes in a branch that's in this repo?

**Comment by cltnschlosser** [comment]
Actually you probably just have to create a branch in this repo with the same commit sha and then this PR would be okay. If you kicked off the tests again.

**Comment by dianaafanador3** [comment]
Hi @cltnschlosser: You can create a pull request directly to our repo, creating a branch from our master branch, add your changes and then creating a pull request, when you do this, the team will review it. 
As an open source project we accept collaboration from everyone in the community and encourage direct contribution to our repo.

**Comment by cltnschlosser** [comment]
> Hi @cltnschlosser: You can create a pull request directly to our repo, creating a branch from our master branch, add your changes and then creating a pull request, when you do this, the team will review it.
> As an open source project we accept collaboration from everyone in the community and encourage direct contribution to our repo.

I would have, but I don't have access to do that :)
```
git push --set-upstream origin cs_excludeCoreHeaders
```
```
ERROR: Permission to realm/realm-cocoa.git denied to cltnschlosser.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by dianaafanador3** [comment]
Hi @cltnschlosser I'm sorry. I'm new and I didn't know about our contribution guidelines (something new I learned today)
Guidelines for contribution to our projects are in the following link https://github.com/realm/realm-cocoa/blob/master/CONTRIBUTING.md.
Also, you would need to sign our CLA mentioned in the below link before we can merge.

Any other questions you have, I'm happy to answer.
Thanks again 😄

**Comment by cltnschlosser** [comment]
I think I’ve signed the CLA in the past.

I just need someone with write access to this repository to make this branch in this repository, and not my fork, so that the cocoapods tests will run and verify this change is correct.

**Comment by tgoyne** [comment]
The commit which added `**` to the paths says it was for pre-1.0 CocoaPods compatibility because we needed different header layouts for 0.39 and 1.0, and obviously we don't need to support 0.39 any more.

**Comment by cltnschlosser** [comment]
@tgoyne Hey, it would be nice to keep this moving.

Could you create a mirror of my branch in this repo so that the tests can be run?

**Comment by dianaafanador3** [comment]
Hey @cltnschlosser I'll help you to get this moving.

**Comment by cltnschlosser** [comment]
Okay, need a copy of this branch in this repo. If it has the same name, looks like you could just trigger CI to run here again. Otherwise need to make a new PR with that branch.

**Comment by cltnschlosser** [comment]
Looks like https://github.com/realm/realm-cocoa/pull/7173 passed :)

**Pull request merged**
