### PR TITLE
Fix the RLMDictionary_Private.h symlink

### PR DESCRIPTION
**Pull request by nicolas255**
~~Fixes the symlink to RLMDictionary_Private.h which causes build errors on case sensitive file systems.~~

See #7344.

### CODE REVIEW

**Comment by nicolas255** [comment]
So this PR is not ready to be merge and actually breaks the build (at least on a case sensitive file system) with the same error as the one I described in #7344. But the reason is not the same and I have absolutely no idea how this happened…

If you manually clone the project, everything is fine. But when the project is added to a Swift package, the symlink in the checkout in the derived data is broken in a weird way:

Screenshot 2021-07-25 at 22 47 33

As you can see here the "?" at the end of the symlink. It's actually a newline character and I have absolutely no idea how it got there…

Here is a hex dump of the symlink after a `git clone`:
```
➜  Realm git:(master) readlink -n RLMDictionary_Private.h > foo
➜  Realm git:(master) hexdump -C foo
00000000  2e 2e 2f 2e 2e 2f 52 65  61 6c 6d 2f 52 4c 4d 44  |../../Realm/RLMD|
00000010  69 63 74 69 6f 6e 61 72  79 5f 50 72 69 76 61 74  |ictionary_Privat|
00000020  65 2e 68                                          |e.h|
00000023
```

And here is a hex dump of the same symlink from the derived data:
```
➜  Realm git:(dba32b4f7) readlink -n RLMDictionary_Private.h > foo
➜  Realm git:(dba32b4f7) hexdump -C foo
00000000  2e 2e 2f 2e 2e 2f 52 65  61 6c 6d 2f 52 4c 4d 44  |../../Realm/RLMD|
00000010  69 63 74 69 6f 6e 61 72  79 5f 50 72 69 76 61 74  |ictionary_Privat|
00000020  65 2e 68 0a                                       |e.h.|
00000024
```

**Comment by leemaguire** [comment]
@nicolas255 does the newline / `?` appear in a fresh project with the same setup?

**Comment by nicolas255** [comment]
@leemaguire I'm not sure what kind of sorcery was at play here but somehow, Xcode kept checking out the wrong commit when specifying `https://github.com/nicolas255/realm-cocoa` on `master` event after clearing out the derived data and reseting the package cache. It was only after restarting Xcode that it decided to check out the correct commit and then it worked… So never mind, the new symlink seems to be working just fine (even if I'm still confused).

And to answer your question, yes, creating another new project actually worked and that is what pushed me to check the commits directly 🙏.

**Review by leemaguire — APPROVED** [review]
We will need to provide a changelog entry for this

**Comment by leemaguire** [comment]
@nicolas255 Could you please sign the CLA located at the bottom of this doc so that we may proceed https://github.com/realm/realm-cocoa/blob/master/CONTRIBUTING.md

**Comment by nicolas255** [comment]
@leemaguire I already did before I submitted the PR (filled up the form using the `nicolas255`).

**Pull request merged**
