### PR TITLE
Update object store and sync

### PR DESCRIPTION
**Pull request by tgoyne**
I don't think there's any user-relevant changes from sync 2.1 to mention in the changelog.

### CODE REVIEW

**Comment by austinzheng** [comment]
I'm a little concerned that upgrading sync seems to have broken the object server tests. I'm looking into it right now.

**Comment by tgoyne** [comment]
Go for it.

**Comment by austinzheng** [comment]
It's ready to merge whenever, assuming my changes are acceptable.

**Comment by tgoyne** [comment]
Change looks fine, but going to wait for it to run on CI in case there's anything goofy in that env.

**Pull request merged**
