### PR TITLE
Add support for Swift 2.0

### PR DESCRIPTION
**Pull request by tgoyne**
Supersedes #2069 and #2202. Moves all swift files that need to be different in 1.2 and 2.0 into version-tagged directories, and then switches symlinks between the two depending on what version of Xcode is being used to build things.

@segiddins @jpsim

### CODE REVIEW

**Comment by segiddins** [comment]
retest this please

**Comment by segiddins** [comment]
retest this please

**Comment by segiddins** [comment]
retest this please

**Comment by segiddins** [comment]
retest this please

**Comment by tgoyne** [comment]
test-package-release now works (other than that the examples have bitcode enabled but the framework doesn't), and gives the following directory structure for the RealmSwift zip:

```
realm-swift-0.93.2
├── examples
│   └── ios
│       ├── swift-1.2
│       │   ├── Backlink
│       │   ├── Encryption
│       │   ├── GroupedTableView
│       │   ├── Migration
│       │   ├── RealmExamples.xcodeproj
│       │   ├── Simple
│       │   └── TableView
│       └── swift-2.0
│           ├── Backlink
│           ├── Encryption
│           ├── GroupedTableView
│           ├── Migration
│           ├── RealmExamples.xcodeproj
│           ├── Simple
│           └── TableView
├── ios
│   ├── swift-1.2
│   │   ├── Realm.framework
│   │   └── RealmSwift.framework
│   └── swift-2.0
│       ├── Realm.framework
│       └── RealmSwift.framework
├── osx
│   ├── swift-1.2
│   │   ├── Realm.framework
│   │   └── RealmSwift.framework
│   └── swift-2.0
│       ├── Realm.framework
│       └── RealmSwift.framework
└── plugin
    ├── RealmPlugin
    ├── RealmPlugin.xcodeproj
    └── Templates
        └── file_templates
            └── Realm\ Model\ Object.xctemplate
                ├── Objective-C
                └── Swift
```

**Comment by segiddins** [comment]
retest this please

**Comment by segiddins** [comment]
retest this please

**Comment by segiddins** [comment]
retest this please

**Comment by segiddins** [comment]
retest this please

**Comment by segiddins** [comment]
Build passed!

**Comment by timanglade** [comment]
This is amaze. Thx y’all! :+1::100::dancers:

**Pull request merged**
