### PR TITLE
Support building framework for watchOS architecture

### PR DESCRIPTION
**Pull request by tgoyne**
Given a core build with bitcode this can now produce a (seemingly) fully working release package, but there's not watchOS sample so there may still be broken things...

See https://github.com/realm/realm-cocoa/pull/2139 for previous conversation.

### CODE REVIEW

**Comment by tgoyne** [comment]
Now uses a core build with bitcode so it should actually work.

**Comment by segiddins** [comment]
Only failure is unrelated

**Comment by tgoyne** [comment]
test-package-release now runs to completion

**Comment by segiddins** [comment]
:+1:

**Pull request merged**
